### ISSUE TITLE
use `emmeans` conditionally?

### ISSUE THREAD

**Issue by IndrajeetPatil** [easystats/modelbased#103]
I am not sure how much we are committed to not having any of the non-base R packages in dependencies. But my understanding was that, apart from `see`, we wanted to use all such packages conditionally. 

But `emmeans` is imported in `modelbased`. Is this by choice? Should we move it to `Suggests` and use it conditionally and ask users to download it?

**Comment by strengejacke** [comment]
modelbased was first completely relying on emmeans, so it made sense to import it. However, I think @DominiqueMakowski wants to focus on `get_predicted()` now. That might change the role of _emmeans_ here, in that it could probably indeed be moved to suggested in the future.

**Comment by DominiqueMakowski** [comment]
It is used by estimate_contrasts and estimate_means but indeed, there's no reason why we couldn't import it conditionally

**Comment by bwiernik** [comment]
There is an argument importing it to reduce friction when users want to use this fairly major functionality. New users of R tend to treat all exceptions as world-ending problems, so a message to install a package may as well be a "what did I do wrong" error message.

**Comment by IndrajeetPatil** [comment]
The way I look at it, and I have no empirical data to back me up here, is that if someone is statistically proficient enough that they wish to compute marginal effects for regression models in R, we can safely assume that they may not be intimidated by a simple message asking them to install a package. They clearly have enough experience with R simply by having a need to use this package.

But that's just my opinion.

**Comment by bwiernik** [comment]
I teach regression modeling to undergraduate and graduate students. R messages being intimidating is probably the number 1 obstacle I encounter with both groups. A big target audience for easystats in my view is students just learning about marginal effects, etc. who are often working in R for the first time.

**Comment by IndrajeetPatil** [comment]
If we zoom out, this criticism (asking users to install packages) will be valid for the entire `easystats` ecosystem since the core packages are littered with install package messages. 

> R messages being intimidating is probably the number 1 obstacle I encounter with both groups. 

I can see base-R messages (like `object of type 'closure' is not subsettable`) being intimidating, but I don't think any of the `easytats` install package messages fall into this category. I believe that they are as simple and as straightforward as English grammar can afford. 

At any rate, my concern is more about consistency. If we are going to advertise `easystats` packages as lightweight alternatives to other popular packages, we need to live up to those expectations.

**Comment by DominiqueMakowski** [comment]
I agree with Brenton about how much intimidating very basic messages can be for new users, especially if no copy/paste solution is given. That said, hopefully, the new function in insight throws an accessible message so it should be okay...

but it's true that since modelbased is likely to be a high-level user-facing package, we don't need to be that strict on imports either? I don't know, there are pros and cons for both :)

**Comment by DominiqueMakowski** [comment]
> the entire easystats ecosystem since the core packages are littered with install package messages.

That's very true, and the worst thing is that we don't even remember how much we require them "optionally" since once you have it installed you forget about it (and as developers we arguably more packages installed than the average user). 

I wonder if we should have somewhere in easystats instructions or a function to install ALL the packages needed to never again encounter such problem. Like "okay if you wanna be able to fully benefit from easystats run this `install_easystats_dependencies()`

**Comment by IndrajeetPatil** [comment]
> I wonder if we should have somewhere in easystats instructions or a function to install ALL the packages needed to never again encounter such problem. Like "okay if you wanna be able to fully benefit from easystats run this install_easystats_dependencies()

I like this idea!

**Comment by mattansb** [comment]
>  if someone is statistically proficient enough that they wish to compute marginal effects for regression models in R, we can safely assume that they may not be intimidated by a simple message asking them to install a package.

People, especially new users, code-and-paste all the time... 
I second @bwiernik experience that:

> R messages being intimidating is probably the number 1 obstacle I encounter with both groups.

I often have students asking me "why is R angry with me?" or thinking that their code failed when a *message* is given, let alone an error...

**Comment by IndrajeetPatil** [comment]
I don't have anything more to add here.

I will let @DominiqueMakowski decide whether to close this issue and the [related PR](#104).

**Comment by bwiernik** [comment]
> I can see base-R messages (like object of type 'closure' is not subsettable) being intimidating, but I don't think any of the easytats install package messages fall into this category. 

My point is that it is a major challenge for me to get students to actually _**read**_ the error message. Students assume that any red/orange/green text = BAD!😱 R is angry! Even things like for example, readr::read_csv() telling them how columns were parsed makes them jump. 

I'm not saying that having Suggested packages is bad, just that if there is a package that provides a major part of the functionality for a package (e.g., I would say emmeans in one of the big things modelbased does and most students learning modelbased as part of a class will need it), we should be okay with importing that. I think it's a different story when a function is rather narrow or a minor part of the package. 

I like the idea of `install_easystats_dependencies()`.

**Comment by strengejacke** [comment]
> That's very true, and the worst thing is that we don't even remember how much we require them "optionally" since once you have it installed you forget about it (and as developers we arguably more packages installed than the average user).

True, however, in many cases where we use packages conditionally, users would use those functions _only_ when they have the packages installed. I see no reason to use bayestestR, when I don't have brms, rstanarm or similar installed.

**Comment by bwiernik** [comment]
Yeah, I think this is a question for each dependency. For bayestestR, we can certainly expect that the bayesian modeling package is installed.
