### ISSUE TITLE
improve website look

### ISSUE THREAD

**Issue by IndrajeetPatil** [easystats/modelbased#105]
This looks weird (I am on Google Chrome):

<img width="882" alt="Screenshot 2021-05-13 at 16 55 08" src="https://user-images.githubusercontent.com/11330453/118143792-03b91300-b40c-11eb-9bc6-bea2bdf65ddd.png">

Is it because of this? I've no idea what this does:

https://github.com/easystats/modelbased/blob/1f3e744b2b2ffd504a16ff194f25a374ec3e37bb/vignettes/visualisation_matrix.Rmd#L13-L14

**Comment by DominiqueMakowski** [comment]
Indeed, let's wait til #101  is merged then we see

**Comment by DominiqueMakowski** [comment]
It's still like that I don't know why the pkgdown file is the same as the other ones...

**Comment by strengejacke** [comment]
Probably because pkgdown fails to rebuild the site and therefore it's not updated?

**Comment by DominiqueMakowski** [comment]
https://github.com/easystats/modelbased/actions/workflows/pkgdown.yml

pkgdown seems to be working fine and the website has been updated 😱 not sure what is going on

**Comment by strengejacke** [comment]
yeah, there are regularly temporary issues.

**Comment by IndrajeetPatil** [comment]
I am pretty sure this weird look traces to our `extra.css` file:
https://github.com/easystats/modelbased/blob/master/pkgdown/extra.css

That's the only different thing `modelbased` is doing compared to other packages.
