### ISSUE TITLE
group-level parameters

### ISSUE THREAD

**Issue by DominiqueMakowski** [easystats/modelbased#112]
Follow up of https://github.com/easystats/parameters/pull/486

What's the most catchy & appropriate name; `estimate_individual`, `estimate_groupspecific`, `estimate_grouplevel`, `estimate_random`, `estimate_individualeffects`, `estimate_scores`, `estimate_individualparameters`...

**Comment by mattansb** [comment]
I like grouplevel.. or groupwise?

**Comment by DominiqueMakowski** [comment]
I like grouplevel too but I do recall @bwiernik made a distinction between group-level and group-specific

**Comment by strengejacke** [comment]
that looks nice!

**Comment by bwiernik** [comment]
"groupspecific" was the most widely suggested when I inquired on Twitter. I would suggest this over "grouplevel" because I find that as being too ambiguous with ranef.

**Comment by bwiernik** [comment]
These are the just the estimated random effects (returned with `ranef()`) right? If so, I like "estimate_random". 

"estimate_group_specific" should return the random effects + fixed effects (what is returned with `coef()`).

**Comment by DominiqueMakowski** [comment]
What I did is I added an argument to `estimate_random` called `deviation = TRUE`:

The description is as follows:

https://github.com/easystats/modelbased/blob/66a45db6e4c69c347ac6a09b67053a68795c274d/R/estimate_random.R#L6

I also mention that in the new [vignette I started](https://easystats.github.io/modelbased/articles/estimate_random.html#correlation-with-empirical-scores): feel free to correct and improve!

**Comment by bwiernik** [comment]
We aren't currently reporting SEs or intervals for the `deviation = FALSE` estimates for lme4 or glmmTMB, right? We shouldn't ever do that for lme4 and should wait to do so for glmmTMB until a proper method is available (Ben Bolker has said he would look into it). For bayesian models we can just derive from the posterior of course.

**Comment by DominiqueMakowski** [comment]
From my current understanding the output of coef

**Comment by mattansb** [comment]
If this is ranef+fixef, I think `estimate_random` is a bad fit :/

**Comment by DominiqueMakowski** [comment]
I don't see it that way, for me it's still the random effects (or rather group-level effects), it's just that they axe expressed in the same "unit" as the fixed effect (rather than being expressed in relation to it), which makes it often easier to interpret but it doesn't change inherently the nature of the coefficients. 

It's a bit like doing `Sepal.Length / Species` instead of `Sepal.Length * Species`, it doesn't change the model, but it shows the effect for each level rather than the "deviation" of the effect from the intercept. That might not be the best example but you see what I mean (i hope)

Afaik it's mostly a "rescaling" of the values for more interpretability rather than a fundamental alteration of the meaning...

**Comment by mattansb** [comment]
> for me it's still the random effects (or rather group-level effects)

To me those aren't the same thing... :/

- Random = distribution around the fixed
- Group level effect = the predicted effect at the level

**Comment by mattansb** [comment]
It actually matters quite a bit.....

``` r
library(lme4)
#> Loading required package: Matrix

m1 <- lmer(mpg ~ 1 + (1|gear), data = mtcars)
m2 <- lmer(mpg ~ 0 + (1|gear), data = mtcars)

# Same
coef(m1)
#> $gear
#>   (Intercept)
#> 3    16.46041
#> 4    24.15615
#> 5    21.22401
#> 
#> attr(,"class")
#> [1] "coef.mer"
coef(m2)
#> $gear
#>   (Intercept)
#> 3    16.05235
#> 4    24.43000
#> 5    21.16515
#> 
#> attr(,"class")
#> [1] "coef.mer"

# Very diff
ranef(m1)
#> $gear
#>   (Intercept)
#> 3   -4.153112
#> 4    3.542629
#> 5    0.610483
#> 
#> with conditional variances for "gear"
ranef(m2)
#> $gear
#>   (Intercept)
#> 3    16.05235
#> 4    24.43000
#> 5    21.16515
#> 
#> with conditional variances for "gear"
```

<sup>Created on 2021-06-03 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by DominiqueMakowski** [comment]
when I said it doesn't matter I didn't mean that the values are the same ^^ naturally they change in respect to their fixed effect. But yeah in your `m2` since intercept = 0 so ranef and coef are the same I'm not sure what point did you have in mind?

**Comment by DominiqueMakowski** [comment]
> Group level effect = the predicted effect at the level

It's not really the *predicted* effect as much as simply the random parameter expressed in "absolute" (i.e., not relative to its fixed effect)

**Comment by mattansb** [comment]
The random part is the predicted deviation of the effect, so when adding the fixed effect it is the predicted effect. AFAIK this is the terminology used for the output of `coef()` here... These values aren't present as-is in the data (because of shrinkage), but they are the predicted values...

**Comment by DominiqueMakowski** [comment]
ah ok I see what you mean by predicted here ^^ (and thank god none of us is from ML)

**Comment by strengejacke** [comment]
`ranef()` returns BLUPs, best linear unbiased *prediction*. The random effects are indeed not estimated, unlike fixed effects.

**Comment by bwiernik** [comment]
Let's change the name to `estimate_blup()`. Also rather than "deviation", I think we need a different name for the argument. "deviation" is really only accurate for specific model specifications. How about `component` with options for "ranef"/"random" or "group_specific"/"total" corresponding to the current deviation = true/false options. 

Explanation:

The more I think about it, the more I really don't like calling the output of coef() "random". It's not. It's the sum of the fixed and random components. I think this is going to encourage confusion on users' parts. See https://wviechtb.github.io/metafor/reference/blup.html and https://github.com/glmmTMB/glmmTMB/issues/691 for some discussion. 

The SEs are absolutely not the same. In most cases, they are not even close. The SE for the output of coef() is sqrt(SE^2_fixed + SE^2_random + 2*cov_fixedrandom). The covariance term tends to be very strong and negative. Because of some of the linear algebra tricks lme4 uses (and Doug Bates' philosophical objections), it's not possible to estimate that covariance with lme4. Ben Bolker has said he is open to glmmTMB reporting these SEs, but there are some implementation details to work out. https://github.com/glmmTMB/glmmTMB/issues/691

**Comment by mattansb** [comment]
I agree with all of this, expect for `estimate_blup()` - no one will have any idea what that means :/

**Comment by DominiqueMakowski** [comment]
Yeah, I think estimate_random is alright and understandable,

what about `type="random"/"total"` or `relative [to the fixed effect] = TRUE/FALSE`?

I'll remove the SE

**Comment by bwiernik** [comment]
I am **really** uncomfortable calling the function `estimate_random` for something that is not just random

**Comment by mattansb** [comment]
Agreed :/ Though I still think `estimate_grouplevel` is both specific enough and ambiguous enough for our needs here...

**Comment by bwiernik** [comment]
I am okay with `estimate_grouplevel` with an argument for "random"/"coefficient" like I described above.

**Comment by bwiernik** [comment]
"condtional" could be another option, but that's probably too confusing given that glmmTMB also uses "conditional" to refer to conditional on the zero-inflated model as well as conditional on group membership.

**Comment by DominiqueMakowski** [comment]
`estimate_grouplevel()` is a fair compromise, I also find `estimate_blups` terribly un-easystatsy

**Comment by DominiqueMakowski** [comment]
I'm worried that `component` or `effect` as an arg will be confusing given that these are also present in parameters() and insight's functions

**Comment by bwiernik** [comment]
How about "what" or "estimate" or "estimate.what"/"estimate_what"?

**Comment by DominiqueMakowski** [comment]
what about one of:
`estimate_grouplevel(model, type = c("random", "total"))`
`estimate_grouplevel(model, type = c("random", "coefficient"))`

**Comment by bwiernik** [comment]
I like it. Let's go with "coefficient"

**Comment by mattansb** [comment]
`estimate_grouplevel(model, type = c("random", "coefficient"))` 👍

**Comment by DominiqueMakowski** [comment]
should `reshape_random()` be renamed `reshape_grouplevel()` or is it fine?

**Comment by DominiqueMakowski** [comment]
actually "coefficient" might not be the best, because it's confusing with the `indices` arg that can be "Coefficient" (to retrieve the column name), what about "full" or "total" or "absolute" or ... "blup"? 😁

**Comment by mattansb** [comment]
Why does it matter if the argument *value* might conflict with another argument's *value*?

**Comment by mattansb** [comment]
>should reshape_random() be renamed reshape_grouplevel() or is it fine?

Hmmm I think should also be changed.

**Comment by DominiqueMakowski** [comment]
> Why does it matter if the argument value might conflict with another argument's value?

`reshape_grouplevel(estimate_grouplevel(x, "coefficient"), "Coefficient")`  or

```
x %>%
  estimate_grouplevel("coefficient") %>%  # lowercase
  reshape_grouplevel("Coefficient")  # uppercase
```

is arguably not the most elegant and clear ^^

**Comment by bwiernik** [comment]
I don't think that clash is that big a deal. It's not as unclear when the arguments are named. 

```r
x %>%
  estimate_grouplevel(type = "coefficient") %>% 
  reshape_grouplevel(indices = "Coefficient") 
```

> "full" or "total" or "absolute" or ... "blup"

"total" should be okay--I'm not thinking of a place where this would be inaccurate. Another option might be "effect" but that's probably not as clear. 

"blup" could refer to either random or total. The best prediction of _what_?

**Comment by DominiqueMakowski** [comment]
Made the fixes, I think we're good for submission for this round, next update will focus on visualisation (#114 which needs lightbeam geoms in see etc.). Will pass it to the winbuilder first and then submit
