### ISSUE TITLE
cov.reduce in emtrends

### ISSUE THREAD

**Issue by DominiqueMakowski** [easystats/modelbased#119]
cov.reduce takes a function or a list of functions (in the case of multiple variables), the name must be the name of the corresponding variable and the function must return the values that we want for that variable. 

Hard to make the function to return some specific stuff since this stuff is stored in external variables. See also:

- https://stackoverflow.com/questions/67881559/

``` r
model <- lm(Petal.Length ~ poly(Sepal.Width, 4), data = iris)

modelbased::model_emtrends(model, modulate = "Sepal.Width")
#> Error in cov.reduce[[nm]](x): unused argument (x)
```

<sup>Created on 2021-06-08 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

@mattansb it seems like the list must be callable with "x"?

**Comment by mattansb** [comment]
Ah, yes.

Then:

```R
for(i in args$modulate) {
  vizdata <- visualisation_matrix(data, target = i, ...)
  var <- attributes(vizdata)$target_specs$varname[1] # Retrieve cleaned varname
  
  fix_values <- function(value) {force(value); function(...) {value}} # ... are ignored
  
  cov.reduce[[var]] <- fix_values(vizdata[[var]])
}
```

**Comment by DominiqueMakowski** [comment]
That worked  🎉 💪 thanks!

``` r
    model <- lm(Petal.Length ~ poly(Sepal.Width, 4), data = iris)
    modelbased::estimate_slopes(model, modulate = "Sepal.Width = c(1, 2, 3)")
#> No numeric variable was specified for slope estimation. Selecting `trend = "Sepal.Width"`.
#> Estimated Marginal Effects
#> 
#> Sepal.Width | Coefficient |    SE |           95% CI | t(145) |      p
#> ----------------------------------------------------------------------
#> 1.00        |       27.69 | 41.65 | [-54.63, 110.01] |   0.66 | 0.507 
#> 2.00        |        7.48 |  5.42 | [ -3.23,  18.19] |   1.38 | 0.169 
#> 3.00        |       -2.44 |  0.59 | [ -3.60,  -1.27] |  -4.14 | < .001
#> Marginal effects estimated for Sepal.Width
```

<sup>Created on 2021-06-08 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

**Comment by mattansb** [comment]
Damn, I am amazing! ;)

**Comment by DominiqueMakowski** [comment]
indeed indeed 😋

**Comment by DominiqueMakowski** [comment]
I hate to be the bearer of bad news @mattansb, but your awesomeness might in question 😢 

Remember this solution? To get the `cov.reduce` format right for emmeans? (the need for it store functions that return a pre-defined output)

https://github.com/easystats/modelbased/blob/78e5c3360b2182c9d6310463319b61827af6630b/R/model_emtrends.R#L39-L42

Turns out (I'm testing with more variables in cov.reduce) that the function's output is overridden at every loop :(

Isolated example:
``` r
content <- list(x1 = c(1, 2, 3), x2 = c("A", "B"))

cov.reduce <- list()

for(var in c("x1", "x2")) {
  values <- content[[var]]
  cov.reduce[[var]] <- local({
    values
    function(x) values
  }) 
} 

cov.reduce$x1()
#> [1] "A" "B"
cov.reduce$x2()
#> [1] "A" "B"
```

<sup>Created on 2021-07-17 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by DominiqueMakowski** [comment]
@bwiernik would you have any idea on how to make this work? 🤔

**Comment by mattansb** [comment]
<sub>impatient, are we??</sub>

It seems not to work because you're not using my suggested solution (why?)

``` r
content <- list(x1 = c(1, 2, 3), x2 = c("A", "B"))

cov.reduce <- list()

fix_values <- function(value) {force(value); function(...) {value}}
for(var in c("x1", "x2")) {
  cov.reduce[[var]] <- fix_values(content[[var]])
} 

cov.reduce$x1()
#> [1] 1 2 3
cov.reduce$x2()
#> [1] "A" "B"
```

<sup>Created on 2021-07-18 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by DominiqueMakowski** [comment]
> impatient, are we??

me since 23h:

![](https://media.giphy.com/media/bQCWmEgKHasZG/giphy.gif)

> you're not using my suggested solution

meh it must me the fault of past-me again, he's really weird sometimes. Apologies and big thanks from current-me tho 😬

**Comment by mattansb** [comment]
🤣 to both
