### ISSUE TITLE
Show spaghetti-plot uncertainty intervals example

### ISSUE THREAD

**Issue by bwiernik** [easystats/modelbased#123]
I was just writing an issue that we should be able to make a plot like the one below until I realized it was already possible!

We should add an example showing this.

``` r
m <- lm(mpg ~ log(disp) + factor(cyl), data = mtcars)
set.seed(1234)
est1 <- modelbased::estimate_expectation(
  model = m, 
  data = "grid", 
  iterations = 1000, 
  keep_iterations = TRUE)
plot(est1)
```

![](https://i.imgur.com/IcyTI5x.png)

<sup>Created on 2021-06-18 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by DominiqueMakowski** [comment]
I was planning to indeed add examples / revamp the current ones to include the automated plots once they are available "on cran" (i.e., once `see` is updated), so for the next release :)
