### ISSUE TITLE
Default visualization_matrix too short?

### ISSUE THREAD

**Issue by bwiernik** [easystats/modelbased#124]
The default length of 10 for visualization_matrix() seems too short (perhaps only in models with factor variables with fairly uneven numeric ranges). If we compare a plot with `data = NULL` to one with `data = "grid"`, the lines look weirdly truncated. They look much better with `length = 500`. Perhaps we should increase the length to such a level?

``` r
m <- lm(mpg ~ log(disp) + factor(cyl), data = mtcars)
est3 <- modelbased::estimate_expectation(
  model = m, 
  data = "grid")
plot(est3)
```

![](https://i.imgur.com/eEMwr7H.png)

``` r
est4 <- modelbased::estimate_expectation(
  model = m, 
  data = NULL)
plot(est4)
```

![](https://i.imgur.com/US069dt.png)

``` r
est5 <- modelbased::estimate_expectation(
  model = m, length = 500,
  data = NULL)
plot(est5)
```

![](https://i.imgur.com/oKYDuGQ.png)

<sup>Created on 2021-06-18 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by DominiqueMakowski** [comment]
Oh boi, this is what spurred the whole moddelbased rewriting recently (https://github.com/easystats/modelbased/issues/100) ^^

The problem of increasing the default length is that it can quickly create super massive dataframes (let's say you grid 3 continuous variables, with `length=10`, 10^3, it already gives you 1000 rows, but with length 40, it ends up with 64,000 rows already)... 

one hairy solution could be to either set this length dynamically (depending on the number of total combination), but that would lead to inconsistent and unpredictable output shape, which is meh. 
Or to somehow detect if the difference between the observed range and the remaining range is large, and if so throw a message suggesting to increase length... 

But that "issue" has bothered me more than necessarily in the past ^^

**Comment by DominiqueMakowski** [comment]
closing this for now
