### ISSUE TITLE
Quick emmeans question (cov.reduce)

### ISSUE THREAD

**Issue by DominiqueMakowski** [easystats/modelbased#133]
I'm wondering about the possibility of merging parts of the code related to emtrends with the one of emmeans. Specifically, if I can specify the "reference grid" in the same way using cov.reduce (as is done with emtrends):

The following doesn't seem to work:

``` r
model <- lm(Sepal.Length ~ Species * Petal.Width, data = iris)

cov.reduce <- list("Species" = function() {c("setosa", "versicolor")})
cov.reduce$Species()
#> [1] "setosa"     "versicolor"

emmeans::emmeans(model, specs = c("Species"), cov.reduce = cov.reduce)
#> NOTE: Results may be misleading due to involvement in interactions
#>  Species    emmean     SE  df lower.CL upper.CL
#>  setosa       5.89 0.6225 144     4.66     7.12
#>  versicolor   5.76 0.0807 144     5.60     5.91
#>  virginica    6.05 0.2168 144     5.62     6.48
#> 
#> Confidence level used: 0.95
```

<sup>Created on 2021-07-18 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

(expected result would be the emmeans of only the two levels specified in cov.reduce)

**Comment by mattansb** [comment]
`cov.reduce` only reduces continuous variables (defined in emmeans as numerics with more that 2 levels).
Perhaps the alternative questions is _why not use `at=list()` for both factors *and* numerics?_

**Comment by DominiqueMakowski** [comment]
and it works also with emtrends... 

``` r
model <- lm(Sepal.Length ~ Species * poly(Petal.Width, 2), data = iris)

at <- list("Species" = c("setosa", "versicolor"))
emmeans::emmeans(model, specs = c("Species"), at = at)
#> NOTE: Results may be misleading due to involvement in interactions
#>  Species    emmean     SE  df lower.CL upper.CL
#>  setosa        3.7 3.5014 141    -3.22    10.62
#>  versicolor    5.8 0.0869 141     5.63     5.98
#> 
#> Confidence level used: 0.95

at <- list("Petal.Width" = c(1, 2, 3))
emmeans::emtrends(model, "Petal.Width", var = c("Petal.Width"), at = at)
#> NOTE: Results may be misleading due to involvement in interactions
#>  Petal.Width Petal.Width.trend   SE  df lower.CL upper.CL
#>            1             0.766 2.15 141    -3.49     5.02
#>            2            -3.145 5.05 141   -13.13     6.84
#>            3            -7.056 8.14 141   -23.15     9.03
#> 
#> Results are averaged over the levels of: Species 
#> Confidence level used: 0.95
```

<sup>Created on 2021-07-18 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>


WAIT BUT it was your idea all along to use `cov.reduce` 😅

**Comment by DominiqueMakowski** [comment]
that facilitates a lot of things lol

**Comment by mattansb** [comment]
`cov.reduce` is useful when there actually is a function.

For example:

``` r
model <- lm(Sepal.Length ~ Species * poly(Petal.Width, 2), data = iris)

emmeans::emtrends(model, "Petal.Width", var = c("Petal.Width"), 
                  cov.reduce = list(Petal.Width = ggeffects::values_at(values = "meansd")))
#> NOTE: Results may be misleading due to involvement in interactions
#>  Petal.Width Petal.Width.trend   SE  df lower.CL upper.CL
#>         0.44            2.9565 1.27 141    0.443     5.47
#>         1.20           -0.0161 2.69 141   -5.326     5.29
#>         1.96           -2.9886 4.93 141  -12.731     6.75
#> 
#> Results are averaged over the levels of: Species 
#> Confidence level used: 0.95
```

<sup>Created on 2021-07-18 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

But if you already know the actual values, at is prob better (and quicker).

**Comment by DominiqueMakowski** [comment]
Yup, but indeed because I use `visualisation_matrix` anyway to pre-compute the values... `at` seems more appropriate. Strange that I didn't manage to make it work somehow before (because I used to use `at` when I used directly emmeans)

**Comment by DominiqueMakowski** [comment]
Another quick emmeans related question for something that I think worked before but now doesn't ? Or maybe I'm just still not fully recovered yet to see the obvious:

``` r
model <- lm(Sepal.Width ~ Species * Petal.Width, data = iris)

m <- emmeans::emmeans(
  model,
  specs = "Species",
  at = list(Species = c("setosa", "versicolor", "virginica"))
)
#> NOTE: Results may be misleading due to involvement in interactions


emmeans::contrast(m, by = "Species", method = "pairwise")
#> Error in if ((misc$estType == "pairs") && (paste(c("", by), collapse = ",") != : missing value where TRUE/FALSE needed
```

<sup>Created on 2021-07-28 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by mattansb** [comment]
`m` has only emmeans for each `Species`. If you `by = "Species"` there is nothing to test `pairwise` - every "subset" has only one emmean.

**Comment by DominiqueMakowski** [comment]
So how can you get the contrasts between the species (collapsed for Petal.Width)? do you need to reform the emmeans or just change the specs in `contrast`? The more I know about emmeans the less I know how to use it ^^

**Comment by DominiqueMakowski** [comment]
ah wait with by = NULL it works now

**Comment by DominiqueMakowski** [comment]
ok nevermind forget my post thanks haha

**Comment by mattansb** [comment]
I think you're not done with your sick-leave lol

**Comment by DominiqueMakowski** [comment]
I have another bug (?) that appeared on my laptop. It is possible that it worked before (or on another machine), but I updated emmeans and brms and it persists. May I check with you @mattansb whether you have it also, and wether it's a legit emmeans bug or wether it's the specifications?

```r
library(brms)

formula <- brms::brmsformula(
  mpg ~ s(wt) + disp + (1|cyl),
  sigma ~ disp + (1|cyl),
  beta ~ disp + (1|cyl),
  family = exgaussian()
)

m <- brm(formula, data = mtcars, refresh = 0)

# This works
emmeans::emtrends(
  m,
  specs = "disp",
  var = "disp",
  at = list("disp" = c(100, 200, 300)))
```
```
 disp disp.trend lower.HPD upper.HPD
  100       0.88      0.39      1.86
  200       0.88      0.39      1.86
  300       0.88      0.39      1.86

Point estimate displayed: median 
HPD interval probability: 0.95
```

```r
# This doesn't
emmeans::emtrends(
  m,
  specs = "wt",
  var = "wt",
  at = list("wt" = c(1, 2, 3)))
```
```
```

**Comment by mattansb** [comment]
```R
library(brms)

formula <- brms::brmsformula(
  mpg ~ s(wt) + disp + (1|cyl),
  sigma ~ disp + (1|cyl),
  beta ~ disp + (1|cyl),
  family = exgaussian()
)

m <- brm(formula, data = mtcars, refresh = 0, iter = 50, chains = 1, backend = "rstan")

emmeans::emtrends(
  m,
  specs = "wt",
  var = "wt",
  at = list("wt" = c(1, 2, 3)))
#>  wt wt.trend lower.HPD upper.HPD
#>   1   -0.328    -0.328    -0.328
#>   2   -0.374    -0.374    -0.374
#>   3   -0.927    -0.927    -0.927
#> 
#> Point estimate displayed: median 
#> HPD interval probability: 0.95
```

Are you using the dev version of `brms`? emmeans+smooths don't work on current CRAN version.

**Comment by DominiqueMakowski** [comment]
right it must be it the update of brms probably failed somewhere along the way, which explains why I thought it worked on another updated machine and not on my current one. Anyway, thanks for checking :)

**Comment by DominiqueMakowski** [comment]
Struggle with curl, stringi and Rcpp here we go 😢

**Comment by DominiqueMakowski** [comment]
iiit's that time again when I come up with a new question for master Mat 😅 

Assuming this model:

```r
formula <- brms::brmsformula(
  mpg ~ s(wt),
  sigma ~ s(wt),
  beta ~ s(wt),
  family = exgaussian()
)

m <- brm(formula, data = mtcars, refresh = 0)
```

is there a way to get the marginal slope / johnson-neyman plot of `wt` on the other distributional components? Because by default as far as I understand it `emtrends` returns the first

**Comment by mattansb** [comment]
The `brms` method for `emmeans` has the following special args:

_from `?brms::`emmeans-brms-helpers`_:

![image](https://user-images.githubusercontent.com/35330040/129436061-10f4e01a-f079-455e-a4a9-35e000acb31a.png)

So:

```R
formula <- brms::brmsformula(
  mpg ~ s(wt),
  sigma ~ s(wt),
  beta ~ s(wt),
  family = brms::exgaussian()
)

m <- brms::brm(formula, data = mtcars, chains = 1, iter = 200)

library(emmeans)
emtrends(m, ~ wt, "wt", dpar = "mu",
         at = list(wt = 1:4))
#>  wt wt.trend lower.HPD upper.HPD
#>   1    -6.16     -8.92    -0.604
#>   2    -8.09    -10.91    -3.825
#>   3    -5.57     -8.29    -4.247
#>   4    -4.66     -8.52    -2.685
#> 
#> Point estimate displayed: median 
#> HPD interval probability: 0.95 

emtrends(m, ~ wt, "wt", dpar = "sigma",
         at = list(wt = 1:4))
#>  wt wt.trend lower.HPD upper.HPD
#>   1    3.998     0.229      7.33
#>   2    3.215    -0.245      6.52
#>   3    1.518    -0.840      2.47
#>   4    0.728    -3.843      1.84
#> 
#> Point estimate displayed: median 
#> HPD interval probability: 0.95 

emtrends(m, ~ wt, "wt", dpar = "beta",
         at = list(wt = 1:4))
#>  wt wt.trend lower.HPD upper.HPD
#>   1   0.2481    -0.641     1.137
#>   2   0.1322    -0.571     0.742
#>   3   0.1278    -0.591     0.393
#>   4   0.0504    -0.817     0.433
#> 
#> Point estimate displayed: median 
#> HPD interval probability: 0.95
```

**Comment by DominiqueMakowski** [comment]
![image](https://user-images.githubusercontent.com/8875533/129436714-6ce270a4-5758-4ede-a8d9-791477ca4c84.png)

**Comment by DominiqueMakowski** [comment]
and it works out of the box, fabulous

```r
formula <- brms::brmsformula(
  mpg ~ s(wt),
  sigma ~ s(wt),
  beta ~ s(wt),
  family = brms::exgaussian()
)

m <- brms::brm(formula, data = mtcars, chains = 1, iter = 200)

plot(modelbased::estimate_slopes(m, trend = "wt", at = "wt", length = 100))
```
![image](https://user-images.githubusercontent.com/8875533/129437714-8da5f806-d559-4bc0-87ee-d1f73b50fa15.png)

```r
plot(modelbased::estimate_slopes(m, trend = "wt", at = "wt", length = 100, dpar = "sigma"))
```
![image](https://user-images.githubusercontent.com/8875533/129437721-8abe58d7-4585-4ad0-be24-63fc565e1bfe.png)

```r
plot(modelbased::estimate_slopes(m, trend = "wt", at = "wt", length = 100, dpar = "beta"))
```
![image](https://user-images.githubusercontent.com/8875533/129437726-08af987a-004e-45bd-a1b7-755f3b8c12b5.png)
