### ISSUE TITLE
example from `{see}` JOSS paper doesn't work anymore

### ISSUE THREAD

**Issue by IndrajeetPatil** [easystats/modelbased#138]
``` r
library(modelbased)

model <- lm(mpg ~ wt * as.factor(cyl), data = mtcars)

estimate_means(model)
#> We selected `at = c("cyl")`.
#> Error in Math.factor(structure(1:3, .Label = c("4", "6", "8"), class = "factor"), : 'round' not meaningful for factors
```

<sup>Created on 2021-08-14 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by IndrajeetPatil** [comment]
From paper

<img width="669" alt="Screenshot 2021-08-14 at 00 11 18" src="https://user-images.githubusercontent.com/11330453/129422979-cfd393fe-9d24-4c21-abc8-1e1208b3fad3.png">

**Comment by DominiqueMakowski** [comment]
woops, thanks i'll give it a look

**Comment by DominiqueMakowski** [comment]
``` r
model <- lm(mpg ~ wt * as.factor(cyl), data = mtcars)

emmeans::emmeans(
  model,
  specs = "cyl",
  at = list(cyl = factor(4, 6, 8))
)
#> Error in Math.factor(structure(NA_integer_, .Label = "8", class = "factor"), : 'round' not meaningful for factors
```

<sup>Created on 2021-08-14 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by DominiqueMakowski** [comment]
It works when the transformation is not taken into account in the specs

``` r
model <- lm(mpg ~ wt * as.factor(cyl), data = mtcars)

emmeans::emmeans(
  model,
  specs = "cyl",
  at = list(cyl = c(4, 6, 8))
)
#> NOTE: Results may be misleading due to involvement in interactions
#>  cyl emmean    SE df lower.CL upper.CL
#>    4   21.4 1.466 26     18.4     24.4
#>    6   19.5 0.967 26     17.5     21.5
#>    8   16.8 0.958 26     14.8     18.8
#> 
#> Confidence level used: 0.95
```

<sup>Created on 2021-08-14 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by DominiqueMakowski** [comment]
I'm not too happy about that patch, but then we shouldn't have made an example with in-formula transformations, these are a really a bad habit 

``` r
library(modelbased)

model <- lm(mpg ~ wt * as.factor(cyl), data = mtcars)

plot(estimate_means(model))
#> We selected `at = c("cyl")`.
#> NOTE: Results may be misleading due to involvement in interactions
```

![](https://i.imgur.com/Dfv68Um.png)

<sup>Created on 2021-08-14 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by DominiqueMakowski** [comment]
![image](https://user-images.githubusercontent.com/8875533/129430690-737946b7-b94a-4ca5-99fd-95d8eea10ee1.png)

Mmh the tests pass locally, not sure why it fails now on GH

**Comment by mattansb** [comment]
> we shouldn't have made an example with in-formula transformations, these are a really a bad habit

_🍗 off topic_: Depends on what transformation... In-formula `scale()` allows for both (1) getting standardized coeffs, and (2) allows `predict` to accept data on the untransformed scale! (similarly, `emmeans` also respects this, and gives the X values on the original scale.)

``` r
library(emmeans)

(m1 <- lm(mpg ~ scale(hp) * am, data = mtcars))
#> 
#> Call:
#> lm(formula = mpg ~ scale(hp) * am, data = mtcars)
#> 
#> Coefficients:
#>  (Intercept)     scale(hp)            am  scale(hp):am  
#>     17.95019      -4.05460       5.27675       0.02762
(m2 <- lm(mpg ~ hp * am, data = mtcars))
#> 
#> Call:
#> lm(formula = mpg ~ hp * am, data = mtcars)
#> 
#> Coefficients:
#> (Intercept)           hp           am        hp:am  
#>  26.6248479   -0.0591370    5.2176534    0.0004029

nd <- data.frame(hp = 4, am = 1)

predict(m1, newdata = nd)
#>        1 
#> 31.60756
predict(m2, newdata = nd)
#>        1 
#> 31.60756

emmeans(m1, ~ hp,
        cov.reduce = \(x) mean(x) + c(-1, 0, 1) * sd(x))
#> NOTE: Results may be misleading due to involvement in interactions
#>     hp emmean    SE df lower.CL upper.CL
#>   78.1   24.6 0.792 28     23.0     26.3
#>  146.7   20.6 0.549 28     19.5     21.7
#>  215.3   16.5 0.783 28     14.9     18.2
#> 
#> Results are averaged over the levels of: am 
#> Confidence level used: 0.95

emmeans(m2, ~ hp,
        cov.reduce = \(x) mean(x) + c(-1, 0, 1) * sd(x))
#> NOTE: Results may be misleading due to involvement in interactions
#>     hp emmean    SE df lower.CL upper.CL
#>   78.1   24.6 0.792 28     23.0     26.3
#>  146.7   20.6 0.549 28     19.5     21.7
#>  215.3   16.5 0.783 28     14.9     18.2
#> 
#> Results are averaged over the levels of: am 
#> Confidence level used: 0.95
```

<sup>Created on 2021-08-14 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by DominiqueMakowski** [comment]
True that this behaviour makes sense - and can be useful - it just makes it more complicated to postprocess 🤷  Tho to be fair most of the problems comes from the typical `as.factor()` in formula used because it saves one line of code ^^

**Comment by mattansb** [comment]
Yeah, `as.factor()` makes no sense in a formula...

**Comment by DominiqueMakowski** [comment]
for some reasons when I devtools' check; I got this:

```
   Running the tests in 'tests/testthat.R' failed.
   Last 13 lines of output:
      2.   \-modelbased::model_emmeans(...)
      3.     \-modelbased:::.guess_emmeans_arguments(model, at, fixed, ...)
      4.       \-modelbased:::.format_emmeans_arguments(model, args, ...)
     -- Error (test-mgcv.R:20:5): estimate_contrasts - mgcv gam ---------------------
     Error: 'length(x) = 2 > 1' in coercion to 'logical(1)'
     Backtrace:
         x
      1. \-modelbased::estimate_contrasts(model)
      2.   \-modelbased::model_emcontrasts(...)
      3.     \-modelbased:::.guess_emcontrasts_arguments(...)
      4.       \-modelbased:::.format_emmeans_arguments(model, args, ...)
     
     [ FAIL 2 | WARN 6 | SKIP 0 | PASS 173 ]
     Error: Test failures
```

(same issue as on GH actions), but when I run the tests locally either via testthat::test_local or directly, no error. + I cannot localize the source of the error. That's typically some mystery for which @strengejacke might know something

**Comment by bwiernik** [comment]
I'll be contrarian here--I think in-formula transformations are absolutely fine

**Comment by strengejacke** [comment]
I [don't like](https://github.com/strengejacke/ggeffects/issues/53) in formula transformations...
