### ISSUE TITLE
Error with plotting preds object

### ISSUE THREAD

**Issue by benjaminwnelson** [easystats/modelbased#140]
When I try to follow the code below, I get an output that states, "Plots are coming in the future version." Any ideas why this would be the case? Thanks!

```
preds <- estimate_relation(model, include_random = TRUE)

plot(preds, ribbon = list(alpha = 0)) # Make CI ribbon transparent for clarity
```

**Comment by IndrajeetPatil** [comment]
Hi, sorry for the troubles.

Can you please try to update to the GitHub versions with the following command, refresh your R session, and then see if it works?

```r
install.packages('easystats', repos = 'https://easystats.r-universe.dev')
```

**Comment by benjaminwnelson** [comment]
Thank you for the response! I tried that and now I am getting the following error.

> Error: package or namespace load failed for ‘modelbased’:
 `object` ‘check_heterogeneity_bias’ is not exported by 'namespace:performance'

**Comment by IndrajeetPatil** [comment]
Sigh.

Can you do the following and then updated all the packages it asks you to update?

```r
remotes::install_github("easystats/easystats")
```

Sorry this is so much pain, but we are doing a lot of reorganizing of functions before the next release and that's what's causing issues.

**Comment by benjaminwnelson** [comment]
No problem at all! You have all made such incredible packages. I am getting this error when I run the code you provided.

![Screen Shot 2021-08-15 at 2 42 52 PM](https://user-images.githubusercontent.com/36683142/129488974-2f63fd5f-bf53-479d-b84b-254081a89130.png)

**Comment by IndrajeetPatil** [comment]
What if you just do:

```r
remotes::install_github("easystats/modelbased")
remotes::install_github("easystats/see")
```

**Comment by strengejacke** [comment]
> object ‘check_heterogeneity_bias’ is not exported by 'namespace:performance'

Can you try updating the _performance_ package from GitHub at first? We are currently trying to push the next release cycle, where packages where undergoing quite some substantial (internal) breaking changes, so it is probably necessary to face the hassle and update packages manually, unless they're pushed to CRAN. :-/

**Comment by benjaminwnelson** [comment]
Thank you for your patience with my reply. After doing those two steps, I now receive this error, even though the package see is installed.

> Error: Package 'see' is required for this function to work.
  Please install it by running install.packages('see').

**Comment by IndrajeetPatil** [comment]
Did you refresh your R session? 

If not, do so and try again. It should work.

**Comment by DominiqueMakowski** [comment]
What I usually do to avoid running into this kind of issues is to, each time after I run the installation fo one package, I restart my R session (or close and reopen R studio): it helps quite a lot

**Comment by benjaminwnelson** [comment]
That worked! Thank you for both!
