### ISSUE TITLE
get rid of NOTE in CRAN checks

### ISSUE THREAD

**Issue by IndrajeetPatil** [easystats/modelbased#157]
https://cran.r-project.org/web/checks/check_results_modelbased.html

```r
Version: 0.7.0
Check: dependencies in R code
Result: NOTE
    Namespace in Imports field not imported from: ‘graphics’
     All declared Imports should be used.
```

**Comment by strengejacke** [comment]
I think this is resolved by https://github.com/easystats/modelbased/commit/e7d10749522f6e38b2dee5229b2240424dc6047c#diff-b6b6854a02ae177f8860f49654ff250c1554d021ae434b6efdbe99d00bdc6055
