### ISSUE TITLE
cran

### ISSUE THREAD

**Issue by DominiqueMakowski** [easystats/modelbased#165]
Please see the problems shown on
<https://cran.r-project.org/web/checks/check_results_modelbased.html>.

Please correct before 2022-01-22 to safely retain your package on CRAN.

**Comment by strengejacke** [comment]
_should_ be fixed already (see https://github.com/easystats/easystats/issues/199) - question is, whether you want to address other things as well?

**Comment by DominiqueMakowski** [comment]
lemme go through my list of 2 billions of unread notifications first and try to summarize what happened during my break ^^

**Comment by DominiqueMakowski** [comment]
submitted

**Comment by DominiqueMakowski** [comment]
I still have this 

```
Examples with CPU (user + system) or elapsed time > 10s
                                         user system elapsed
visualisation_recipe.estimate_predicted 13.36   0.18   13.55
```

despite reducing it to max:

https://github.com/easystats/modelbased/blob/29f274bfacb0759d3a455158fc4bb5573604c095/R/visualisation_recipe.estimate_predicted.R#L13-L22

what to do?

**Comment by IndrajeetPatil** [comment]
Maybe also not run a few or all of the examples?

```r
#' \dontrun{\donttest{ ... }}
```

**Comment by DominiqueMakowski** [comment]
But I thought `donttest` was sufficient and wasn't counted in the timing on CRAN 🤔

**Comment by IndrajeetPatil** [comment]
Yeah, strange indeed.

Can you try skipping more examples and then submitting again?

**Comment by IndrajeetPatil** [comment]
Maybe even with some examples skipped, the check time is still too high for CRAN machines.

**Comment by DominiqueMakowski** [comment]
thanks, package modelbased_0.7.1.tar.gz is on its way to CRAN.
