### ISSUE TITLE
cran update

### ISSUE THREAD

**Issue by DominiqueMakowski** [easystats/modelbased#171]
Please see the problems shown on
<https://cran.r-project.org/web/checks/check_results_modelbased.html>.

Please correct before 2022-03-04 to safely retain your package on CRAN.

**Comment by strengejacke** [comment]
https://github.com/easystats/modelbased/pull/170

**Comment by strengejacke** [comment]
https://github.com/easystats/easystats/issues/199#issuecomment-1041205017

**Comment by strengejacke** [comment]
I think you can submit _modelbased_ to CRAN, after doing win-builder checks. Everything should be fine.

**Comment by strengejacke** [comment]
What's the current state of submission?

**Comment by strengejacke** [comment]
@DominiqueMakowski ?

**Comment by IndrajeetPatil** [comment]
Seems to be on CRAN. Thanks, Dom!

https://cran.r-project.org/web/packages/modelbased/index.html
