### ISSUE TITLE
CRAN: update before 10 April

### ISSUE THREAD

**Issue by DominiqueMakowski** [easystats/modelbased#181]
Please see the problems shown on
<https://cran.r-project.org/web/checks/check_results_modelbased.html>.

Please correct before 2022-04-10 to safely retain your package on CRAN.

**Comment by strengejacke** [comment]
We're currently waiting for _insight_ to be published first, but it's still under consideration, due to a note when submitting.

**Comment by strengejacke** [comment]
@IndrajeetPatil we should submit _datawizard_ shortly after _insight_...

**Comment by IndrajeetPatil** [comment]
Yes sir! I've been waiting to see _insight_ on CRAN.

**Comment by strengejacke** [comment]
me too ;-)

**Comment by strengejacke** [comment]
insight -> datawizard -> modelbased should work, or do we need bayestestR, too?

**Comment by strengejacke** [comment]
@DominiqueMakowski Is the error already resolved?

**Comment by DominiqueMakowski** [comment]
I think so, yes bayestestR is priority after datawizard it has a pending deadline too ^^

**Comment by strengejacke** [comment]
ok, but modelbased in indepdendent from bayestestR, right?

**Comment by DominiqueMakowski** [comment]
mmh yeah true, I can submit both at the same time (even though modelbased will likely need parameters https://github.com/easystats/parameters/pull/686, but I'll skip the new tests on CRAN for this release)

**Comment by strengejacke** [comment]
yes, better skip that for now, else we'll not even come close to the deadlines if we need another package submitted first ;-)

**Comment by strengejacke** [comment]
Ok, we see the CRAN error now on GitHub, too. I'm not sure, but it's likely due to the recent emmeans-update (https://cran.r-project.org/web/packages/emmeans/index.html). We should check and debug locally using the new emmeans version.

**Comment by strengejacke** [comment]
(btw., a good example why it's useful to have curated NEWS files :-):

```
emmeans 1.7.3
argument change ref_grid(..., transform = ...) now should be ref_grid(..., regrid = ...) to avoid confusing transform with the tran option (which kind of does the opposite). If we match transform and don’t match tran, it will still work, but a message is displayed with advice to use regrid instead.
Repairs to averaging support (#324). Previous versions were potentially dead wrong except for models created by lm() (and maybe some of those were bad too)
Added a which argument to emm() to select which list elements to pass to multcomp::glht()
Support for rank-deficient gls models (note that nlme allows such models with gls, but not lme)
Bug in lqm / lqmm support (#340)
Other minor corrections (e.g. #334)
```

**Comment by strengejacke** [comment]
@DominiqueMakowski insight and datawizard are on CRAN, so you can proceed with modelbased.

**Comment by DominiqueMakowski** [comment]
package modelbased_0.8.0.tar.gz has been auto-processed.
The auto-check found additional issues for the *last* version released on CRAN:
  M1mac <https://www.stats.ox.ac.uk/pub/bdr/M1mac/modelbased.out>
CRAN incoming checks do not test for these additional issues.
Hence please reply-all and explain: Have these been fixed?

**Comment by DominiqueMakowski** [comment]
Seems related to something like `Error in xj[i] : invalid subscript type 'list'`

**Comment by strengejacke** [comment]
I'm not sure, but I _guess_ this is fixed. If you look at the output from that example, you see:

> No numeric variable was specified for slope estimation. Selecting `trend = "Petal.Length"`.

However, in the example, `Petal.Length` is specified for `trend`, so this was an issue in properly detecting the data. I think we have fixed this. Maybe @IndrajeetPatil can check, he has a Mac? Can you install latest insight and datawizard, and then check that example (`?estimate_slopes`) locally?

**Comment by strengejacke** [comment]
Else, just remove the 2nd mgcv example ;-)

**Comment by IndrajeetPatil** [comment]
I can confirm that M1 mac issues have been fixed. 

All tests and examples run without any problems.

**Comment by DominiqueMakowski** [comment]
Thanks, on its way to CRAN.

**Comment by strengejacke** [comment]
@DominiqueMakowski can you commit your latest changes? The description on GH is still version 0.7.2.1
