### ISSUE TITLE
31/05 deadline

### ISSUE THREAD

**Issue by DominiqueMakowski** [easystats/modelbased#183]
Please see the problems shown on
<https://cran.r-project.org/web/checks/check_results_modelbased.html>.

Please correct before 2022-05-31 to safely retain your package on CRAN.

**Comment by strengejacke** [comment]
I think @vincentarelbundock is fixing this, but anyway, we should use suggested packages only conditionally.

**Comment by vincentarelbundock** [comment]
`marginaleffects` 0.5.0 is on CRAN now. Sorry for the trouble.

For the record I'll note that I was given until the 15th to submit a new version. I submitted on the 14th and my packaged was archived anyway. So not only are those emergency 2-week deadlines exceedingly short, we also need to plan a buffer in case something else is wrong with the submission or it stays in queue too long.

FWIW, I plan to skip most (all?) of my tests on CRAN from now on.

**Comment by strengejacke** [comment]
> FWIW, I plan to skip most (all?) of my tests on CRAN from now on.

I did this for most tests in _parameters_, too, I think, but a CRAN team member complained about skipping almost _all_ tests ;-)

**Comment by vincentarelbundock** [comment]
The system is just not well suited for packages like ours, which are designed for *interoperability* and must test against 50+ other packages.

I keep getting emergency emails from BDR when some tests fail at 1e-6 tolerance, because some upstream package changed a seed or something. And the two week deadline waayyyy too short.

In the latest version, I just commented out the whole content of `tests/testthat.R`, so they don't even see the skipped test in the log.

**Comment by IndrajeetPatil** [comment]
@DominiqueMakowski The tests are still failing, so we definitely need to make a new _modelbased_ release soon:
https://cran.r-project.org/web/checks/check_results_modelbased.html

**Comment by strengejacke** [comment]
See https://github.com/easystats/parameters/commit/5aa9be71291e62e4a11f3f202daa3f4a5ab505ea

**Comment by IndrajeetPatil** [comment]
@DominiqueMakowski I have submitted _modelbased_ to win-builder-devel, so you should get an email soon.

Hopefully, there are no errors or warnings.

**Comment by DominiqueMakowski** [comment]
https://win-builder.r-project.org/aY3d4n8pQr49

**Comment by strengejacke** [comment]
These must be pretty old issues - the package isn't named _estimate_ any more since ages...

**Comment by IndrajeetPatil** [comment]
I have already fixed all those issues. We should be ready for a submission here.

**Comment by strengejacke** [comment]
Great!
