### ISSUE TITLE
cran update

### ISSUE THREAD

**Issue by DominiqueMakowski** [easystats/modelbased#196]
Please see the problems shown on
<https://cran.r-project.org/web/checks/check_results_modelbased.html>.

Please correct before 2022-08-20 to safely retain your package on CRAN.

The CRAN Team

**Comment by strengejacke** [comment]
_insight_ is submitted, _datawizard_ ready for submission. I'm not sure whether _modelbased_ needs to go before _datawizard_, or if that doesn't matter? (see https://github.com/easystats/easystats/issues/256) @IndrajeetPatil

**Comment by IndrajeetPatil** [comment]
_modelbased_ can be submitted.

In https://github.com/easystats/modelbased/commit/005e2ba80b967accc4a9e7587605ef48284e3a73, I had removed its reliance on `datawizard::to_numeric()`, so there shouldn't be any problems.

**Comment by IndrajeetPatil** [comment]
I just submitted it to win-builder. @DominiqueMakowski You should receive an email soon. 

Let's see if it works with the CRAN version of _datawizard_. I think it should.

**Comment by IndrajeetPatil** [comment]
Dom, did you get any email from win-builder?

**Comment by strengejacke** [comment]
I think #200 should fix some issues, also with _emmeans_. We should merge that PR if tests pass (some checks will fail due to _emmeans_ requiring R >= 4.1(!))

**Comment by strengejacke** [comment]
Looks like vignettes/estimate_grouplevel.rmd needs to be fixed.

**Comment by DominiqueMakowski** [comment]
> this notification has been generated automatically.
Your package modelbased_0.8.1.4.tar.gz has been built (if working) and checked for Windows.
Please check the log files and (if working) the binary package at:
https://win-builder.r-project.org/114DU96fI0HB
The files will be removed after roughly 72 hours.
Installation time in seconds: 11
Check time in seconds: 167
Status: OK


Will look again into all of this tomorrow once I'm back in office

**Comment by strengejacke** [comment]
I think all bugs are fixed now, and if win-builder passes, everything should be ok to submit (you need to set the version number to 0.8.2 or so, though). I think the other issues can wait after submission.

**Comment by DominiqueMakowski** [comment]
submitted

**Comment by bwiernik** [comment]
We should try to transition to {marginaleffects} as a backend in the next few releases

**Comment by DominiqueMakowski** [comment]
thanks, package modelbased_0.8.5.tar.gz is on its way to CRAN.

**Comment by DominiqueMakowski** [comment]
> We should try to transition to {marginaleffects} as a backend in the next few releases

Agreed
