### ISSUE TITLE
estimate_expectation truncated_poisson glmmTMB bug

### ISSUE THREAD

**Issue by mebrooks** [easystats/modelbased#217]
I was running checks for a new glmmTMB CRAN release and found that R crashes when running `estimate_expectation` on a model with the `truncated_poisson` family as in `test-glmmTMB.R`. It may have been caused by [this commit](https://github.com/glmmTMB/glmmTMB/commit/1e37cbecdbe60773f19dbab4b60317b4bf46f056) where we changed how predictions are made for truncated families.

**Comment by strengejacke** [comment]
Thanks, what is your expected time schedule for submitting glmmTMB to CRAN?

**Comment by mebrooks** [comment]
I'm running the rest of the checks today. We were hoping to submit any day now, but I want to give you some chance to fix the problem.

**Comment by mebrooks** [comment]
Sorry, I didn't see an email when you asked. The master branch is the same as we plan to submit except for incrementing the version number.

**Comment by mebrooks** [comment]
Fixed with https://github.com/glmmTMB/glmmTMB/pull/876
