### ISSUE TITLE
CRAN submission

### ISSUE THREAD

**Issue by strengejacke** [easystats/modelbased#221]
@DominiqueMakowski for the forthcoming _insight_ update, it would be good to submit _modelbased_ first, to (hopefully) ensure a smooth submission process. Can you push a new release to CRAN?

**Comment by DominiqueMakowski** [comment]
okay I'll do today

**Comment by DominiqueMakowski** [comment]
submitted, what about bayestestR / report should I submit too? (sorry I'm been under water)

**Comment by DominiqueMakowski** [comment]
package modelbased_0.8.5.2.tar.gz does not pass the incoming checks automatically, please see the following pre-tests:
Windows: <https://win-builder.r-project.org/incoming_pretest/modelbased_0.8.5.2_20230112_025411/Windows/00check.log>
Status: 1 ERROR, 1 NOTE

**Comment by DominiqueMakowski** [comment]
it seems like a brms error doesn't it

**Comment by strengejacke** [comment]
> '0.8.5.2'

You submitted a dev-version 🤣 

Just increase the version number to something like 0.8.3 and it should work.

**Comment by DominiqueMakowski** [comment]
🙈

**Comment by strengejacke** [comment]
> submitted, what about bayestestR / report should I submit too? (sorry I'm been under water)

These are not affected by the changes in _insight_, I think. @vincentarelbundock testet all remaining packages and found no revdep-isuses. But if you feel it's time to submit an update for those as well, just do it. Else, there's no hurry.

**Comment by DominiqueMakowski** [comment]
I'll submit otherwise all the packages I maintain are trailing behind and it looks bad 😅

**Comment by DominiqueMakowski** [comment]
package modelbased_0.8.6.tar.gz does not pass the incoming checks automatically, please see the following pre-tests:
Windows: <https://win-builder.r-project.org/incoming_pretest/modelbased_0.8.6_20230112_080812/Windows/00check.log>
Status: 1 ERROR, 2 NOTEs

**Comment by strengejacke** [comment]
hm, strange. Maybe skip this test for now? Honestly, it's really hassling to get stan tests working...
Also, https://cranlogs.r-pkg.org/ seems to offline / has moved? we should remove that URL from readme.

**Comment by strengejacke** [comment]
I have updated the readme... Maybe also send to winbuilder before sending to CRAN? This will catch most of the issues during submission.

**Comment by IndrajeetPatil** [comment]
_cranlogs_ is back up and running. So you can add the links back in if you want.

**Comment by IndrajeetPatil** [comment]
We should make sure that we close #216 and #219 before submission, though.

**Comment by DominiqueMakowski** [comment]
package modelbased_0.8.6.tar.gz is on its way to CRAN.
