### ISSUE TITLE
CRAN submission (deadline 20/02)

### ISSUE THREAD

**Issue by DominiqueMakowski** [easystats/modelbased#247]
Dear maintainer,

Please see the problems shown on
<https://cran.r-project.org/web/checks/check_results_modelbased.html>.

Please correct before 2024-02-20 to safely retain your package on CRAN.

The CRAN Team

**Comment by strengejacke** [comment]
Should be fixed in #246

**Comment by DominiqueMakowski** [comment]
on cran
