### ISSUE TITLE
CRAN failures

### ISSUE THREAD

**Issue by IndrajeetPatil** [easystats/modelbased#258]
https://cloud.r-project.org/web/checks/check_results_modelbased.html

**Comment by strengejacke** [comment]
See https://github.com/easystats/modelbased/pull/257 :-)

**Comment by DominiqueMakowski** [comment]
Ripley:

>> Please see the problems shown on
>> <https://cran.r-project.org/web/checks/check_results_modelbased.html>.

We have had to exclude this from the Fedora checks as it had to be
killed (twice) when using over 50GB of VM and causing the machine to
swap.  This only happened on the update to some other package (insight?)

The CRAN policy calls that 'anti-social'.



---

And from the M1mac additional issue

+ ## Don't show:
+ }) # examplesIf
Loading required package: mgcv
Loading required package: nlme
This is mgcv 1.9-1. For overview type 'help("mgcv-package")'.
 > model <- mgcv::gam(Sepal.Width ~ s(Petal.Length), data = iris)
 > slopes <- estimate_slopes(model, at = "Petal.Length", length = 50)
No numeric variable was specified for slope estimation. Selecting `trend
= "Peta
l.Length"`.
Warning: Argument `at` is deprecated and will be removed in a future
release.
   Please use `by` instead.
 > summary(slopes)
Warning: Function `data_find()` is deprecated and will be removed in a
future
   release. Please use `extract_column_names()` instead.
Error: vector memory limit of 16.0 Gb reached, see mem.maxVSize()
Execution halted

as well as incorrect results.

**Comment by IndrajeetPatil** [comment]
> it had to be killed (twice) when using over 50GB of VM and causing the machine to swap

Wow. What test or example is making such a huge memory impact? Can we reproduce this on GHA?

**Comment by strengejacke** [comment]
I can't think of any changes in _insight_ that could have such an impact?

**Comment by IndrajeetPatil** [comment]
My guess is that this might be coming from some modeling package we are using in example. Either that or we have some recursive function misbehaving.
