### ISSUE TITLE
CRAN initial release

### ISSUE THREAD

**Issue by DominiqueMakowski** [easystats/modelbased#32]
I think this one can be submitted. Thoughts?

**Comment by strengejacke** [comment]
We could improve or prepare functions for plotting. Eg, `visualization_marix()` could save the terms in questions as attribute, so when we plot from `estimate_link()`, we know which variable is mapped to the x axis, which to the color scale etc.

**Comment by DominiqueMakowski** [comment]
Good idea. 

- `estimate_means` (we could use the half-violin dotploplot in background?) could be easily 
- For contrasts, the lighthouse is a ReVoLuTiOnArY feature IMO in theory, but needs to be improved for the cases of nested contrasts (might use the plotting for means as a basis)
- For `estimate_smooth`, quite easy too, we could plot the smooth term, and then simply add dashed vlines at every breakpoint (change in slope)

Extension of support to other packages (besides rstanarm, glms and merMod) is also a goal. I think that the current implementation will make that one quite easy. It might be already compatible with some other packages, but we just need to create, and test, the methods.

**Comment by DominiqueMakowski** [comment]
After #38, I think estimate can be submitted as it is pretty much basic feature-ready

**Comment by DominiqueMakowski** [comment]
shall we go ahead and submit his?

**Comment by strengejacke** [comment]
Yes, I think it's quite complete for initial release.
