### ISSUE TITLE
CI for merMod predictions

### ISSUE THREAD

**Issue by DominiqueMakowski** [easystats/modelbased#34]
@strengejacke:

> There is a solution by Ben Bolker, here
> http://bbolker.github.io/mixedmodels-misc/glmmFAQ.html#predictions-andor-confidence-or-prediction-intervals-on-predictions
> 
> I have generalized this function and made it a bit more robust to different models:
> 
> https://github.com/strengejacke/ggeffects/blob/master/R/predict_standard_errors_from_vcov.R

**Comment by mattansb** [comment]
Q: Whats wrong with the result `emmeans` gives? 🤔

**Comment by DominiqueMakowski** [comment]
@mattansb I think that we were referring here to provide CI for `predict.merMod` (i.e., without emmeans)

**Comment by DominiqueMakowski** [comment]
should be fixed now by get_predicted

**Comment by bwiernik** [comment]
We should be cautious/give a message about the absence of accounting for uncertainty in the REs, direct folks to an MCMC estimator. 

Also note that we should not use the intervals given there for the coef() output. The fixed and random parts are not orthogonal in estimation in most cases.
