### ISSUE TITLE
standardize = TRUE does not return Cohen's d

### ISSUE THREAD

**Issue by mattansb** [easystats/modelbased#43]
Instead it returns something closer to a beta, which is standardized by `sd(y)`, whereas Cohen's d is standardized by `sd(errors)` - which becomes more complicated with mixed models, or with interactions.

I suggest correcting the docs, 
Or if you're brave, try playing with `emmeans::eff_size`.

**Comment by DominiqueMakowski** [comment]
Agreed!

didn't have the time to play with emmeans::eff_size, what do you think of it?

**Comment by mattansb** [comment]
I also haven't used it yet (I just do `effectsize::t_to_d`)
