### ISSUE TITLE
download models only for local running tests

### ISSUE THREAD

**Issue by strengejacke** [easystats/modelbased#46]
Since downloading models is increasingly causing troubles with CRAN checks, we should fit the models in tests directly, or only run tests locally when downloading models from GitHub is required. We should prepare this in time (performance, insight and parameters are already fixed), to be ready for a possible update.

**Comment by DominiqueMakowski** [comment]
> Since downloading models is increasingly causing troubles with CRAN checks

What makes you say that?

**Comment by strengejacke** [comment]
![image](https://user-images.githubusercontent.com/26301769/74222771-7f7e5a00-4cb5-11ea-91a9-8056794bd00f.png)

If you look into the check details, you'll see that each time, the problem is

> Could not resolve host: raw.githubusercontent.com
