### ISSUE TITLE
Invalid URL

### ISSUE THREAD

**Issue by strengejacke** [easystats/modelbased#48]
Can't rebuild vignette `estimate_smooth`, because URL to data is invalid:

https://github.com/easystats/modelbased/blob/d9919b7ae09c7b014effffc5c435179248ee5487/vignettes/estimate_smooth.Rmd#L107

**Comment by DominiqueMakowski** [comment]
AAaaaaah right thanks for mentioning!!!! ^^ I delete this yesterday my bad, will re-add it 😬
