### ISSUE TITLE
issue with estimate_contrasts

### ISSUE THREAD

**Issue by goesjon** [easystats/modelbased#51]
Hello,

I have the following problem with the function "estimate_contrasts()": 

model <- lmer(data = Data, observationVariable ~ factor1 * factor2 + (1|subjectID))
{no errors or warnings here}
contrasts <- estimate_contrasts(model, levels = "factor1", fixed = "factor2")
{Error in names(levelcols) <- c("Level1", "Level2") : 
 'names' attribute [2] must be the same length as the vector [0]}

No matter what I do, I always get this error using "estimate_contrasts()" with the "fixed" option. What do I do wrong? Why does the vector have a length of [0]? 

Help would be very much appreciated. 

Thank you very much and stay healthy!

**Comment by DominiqueMakowski** [comment]
reproducible code:

```r
library(lme4)
df <- iris
df$factor1 <- ifelse(df$Sepal.Width > 3, "A", "B")
df$factor2 <- ifelse(df$Petal.Length > 3.5, "C", "D")

model <- lmer(Petal.Width ~ factor1 * factor2 + (1|Species), data=df)
 estimate_contrasts(model, fixed = "factor2")
```

I will investigate

**Comment by DominiqueMakowski** [comment]
Could try updating from dev `devtools::install_github("easystats/modelbased", "dev")` and see if that works?

**Comment by goesjon** [comment]
Hello @DominiqueMakowski 

thank you very much for your messages and for you reproducible code. Indeed, the "# Doesn't work" part does not work, whereas the "# Works ??" part works. I updated with: 

`devtools::install_github("easystats/modelbased", "dev")`

but it still does not work. 

I found a kind of work around: 

`estimate_contrasts(model, levels = ~ "factor1 * factor2")`

but it is not really the same. Tell me, when you found out something. 

Thank you very much for your help.

Jonathan

**Comment by DominiqueMakowski** [comment]
As the `#doesn't work` code now works at my place, could you reprex what's happening on your computer, including the error message?

``` r
library(modelbased)
df <- iris
df$factor1 <- ifelse(df$Sepal.Width > 3, "A", "B")
df$factor2 <- ifelse(df$Petal.Length > 3.5, "C", "D")

# Now works
model <- lm(Petal.Width ~ factor1 * factor2, data=df)
estimate_contrasts(model, fixed = "factor2")
#> Level1 | Level2 | factor2 | Difference |   SE |         95% CI |     t |  df |      p | Difference (std.)
#> ---------------------------------------------------------------------------------------------------------
#> A      |      B |       C |       0.40 | 0.08 | [ 0.25,  0.55] |  5.29 | 146 | < .001 |              0.52
#> A      |      B |       D |      -0.26 | 0.10 | [-0.46, -0.06] | -2.54 | 146 | 0.012  |             -0.34
```

<sup>Created on 2020-04-15 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by goesjon** [comment]
Hello @DominiqueMakowski 

thank you very much for your help. The "#doesn't work" part now (suddenly, I am really sorry) works also at my place. Also my original code (lmer model) now works. Great! 

Thank you very much again. I close the issue.

**Comment by franrodalg** [comment]
Hi @DominiqueMakowski,

Sorry for resurfacing this, but I have just installed the development version because I was facing the same issue with my data, and I don't get the expected output for

```estimate_contrasts(iris_fit, fixed = "factor2")```

Instead, I get contrasts for a single level of the "fixed" factor:

```
Level1 | Level2 | factor2 | Difference |   SE |         95% CI |     t |  df |     p | Difference (std.)
--------------------------------------------------------------------------------------------------------
A      |      B |       D |      -0.26 | 0.10 | [-0.46, -0.06] | -2.54 | 146 | 0.012 |             -0.34
```

I tried with my own data and it causes the same behaviour. With multiple  "fixed" factors, I only get a level from each.

Thanks so much for your work.

Cheers,
- Fran

**Comment by DominiqueMakowski** [comment]
@franrodalg could you share a reproducible example so I can investigate? thanks!

**Comment by franrodalg** [comment]
thanks for replying so quickly @DominiqueMakowski 

I have run exactly the same code as above:
```
df <- iris
df$factor1 <- ifelse(df$Sepal.Width > 3, "A", "B")
df$factor2 <- ifelse(df$Petal.Length > 3.5, "C", "D")

# Doesn't work
model <- lm(Petal.Width ~ factor1 * factor2, data=df)
estimate_contrasts(model, fixed = "factor2")
```

**Comment by DominiqueMakowski** [comment]
What would you expect? Here it is rather expected, as essentially by default the contrast will be made between the `factor1` condition (so between A and B), and `factor2` is *fixed*, meaning maintained at one value. You can pass `factor2` to `modulate`, in which case it will show the contrast at each value of factor2:

```r
> estimate_contrasts(model, modulate = "factor2")
Level1 | Level2 | factor2 | Difference |   SE |         95% CI |     t |  df |      p | Difference (std.)
---------------------------------------------------------------------------------------------------------
A      |      B |       C |       0.40 | 0.08 | [ 0.25,  0.55] |  5.29 | 146 | < .001 |              0.52
A      |      B |       D |      -0.26 | 0.10 | [-0.46, -0.06] | -2.54 | 146 | 0.012  |             -0.34
```

Hope that clarifies

**Comment by franrodalg** [comment]
I was expecting the same output that you posted above:

> As the `#doesn't work` code now works at my place, could you reprex what's happening on your computer, including the error message?
> 
> ```r
> library(modelbased)
> df <- iris
> df$factor1 <- ifelse(df$Sepal.Width > 3, "A", "B")
> df$factor2 <- ifelse(df$Petal.Length > 3.5, "C", "D")
> 
> # Now works
> model <- lm(Petal.Width ~ factor1 * factor2, data=df)
> estimate_contrasts(model, fixed = "factor2")
> #> Level1 | Level2 | factor2 | Difference |   SE |         95% CI |     t |  df |      p | Difference (std.)
> #> ---------------------------------------------------------------------------------------------------------
> #> A      |      B |       C |       0.40 | 0.08 | [ 0.25,  0.55] |  5.29 | 146 | < .001 |              0.52
> #> A      |      B |       D |      -0.26 | 0.10 | [-0.46, -0.06] | -2.54 | 146 | 0.012  |             -0.34
> ```
> 
> Created on 2020-04-15 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)

**Comment by DominiqueMakowski** [comment]
Somehow I think that old code was not doing what it should have done by then 😅 I think it's clearer if the `fixed` arg maintains, and `modulate` modulates. Apologies for the unexpected change I didn't know it broke previous behaviour!

**Comment by franrodalg** [comment]
Sure, thanks, no problem :)

Changing to `modulate` seems to work for that case, but for a slightly more complex model I think it behaves unexpectedly:

```
df <- iris
df$factor1 <- ifelse(df$Sepal.Width > 3, "A", "B")
df$factor2 <- ifelse(df$Petal.Length > 3.5, "C", "D")
df$factor3 <- ifelse(df$Sepal.Length > 5, "E", "F")

model <- lm(Petal.Width ~ factor1 * factor2 * factor3, data=df)
modelbased::estimate_contrasts(model, modulate = c("factor2"))
```
```
Level1 | Level2 | factor2 | Difference |   SE |         95% CI |     t |  df |      p | Difference (std.)
---------------------------------------------------------------------------------------------------------
A E    |    A F |       D |       0.05 | 0.10 | [-0.22,  0.31] |  0.48 | 143 | 0.632  |              0.06
A E    |    B E |       D |      -0.77 | 0.24 | [-1.40, -0.14] | -3.28 | 143 | 0.007  |             -1.01
A E    |    B F |       D |      -0.14 | 0.12 | [-0.46,  0.17] | -1.20 | 143 | 0.467  |             -0.18
A F    |    B F |       D |      -0.19 | 0.12 | [-0.51,  0.13] | -1.57 | 143 | 0.355  |             -0.25
A - E  |  A - F |       C |            |      |                |       |     |        |                  
A - E  |  B - E |       C |       0.40 | 0.07 | [ 0.20,  0.60] |  5.37 | 143 | < .001 |              0.52
A - E  |  B - F |       C |       0.30 | 0.33 | [-0.57,  1.17] |  0.93 | 143 | 1.000  |              0.40
A - F  |  B - F |       C |            |      |                |       |     |        |                  
B E    |    A F |       D |       0.82 | 0.24 | [ 0.19,  1.45] |  3.47 | 143 | 0.004  |              1.08
B E    |    B F |       D |       0.63 | 0.25 | [-0.02,  1.29] |  2.58 | 143 | 0.044  |              0.83
B - E  |  A - F |       C |            |      |                |       |     |        |                  
B - E  |  B - F |       C |      -0.10 | 0.32 | [-0.96,  0.76] | -0.30 | 143 | 1.000  |             -0.13
```

**Comment by DominiqueMakowski** [comment]
Indeed 😁 I'll look into it tomorrow

**Comment by franrodalg** [comment]
thanks!

**Comment by DominiqueMakowski** [comment]
It seems like the error actually originates in `emmeans`:

``` r
data <- iris
    data$factor1 <- ifelse(data$Sepal.Width > 3, "A", "B")
    data$factor2 <- ifelse(data$Petal.Length > 3.5, "C", "D")
    data$factor3 <- ifelse(data$Sepal.Length > 5, "E", "F")

    model <- lm(Petal.Width ~ factor1 * factor2 * factor3, data=data)

    emmeans::contrast(emmeans::ref_grid(model, nesting=NULL), by = "factor3", method = "pairwise")
#> factor3 = E:
#>  contrast  estimate     SE  df t.ratio p.value
#>  A,C - B,C    0.400 0.0745 143  5.365  <.0001 
#>  A,C - A,D    1.727 0.0933 143 18.511  <.0001 
#>  A,C - B,D    0.954 0.2345 143  4.069  0.0004 
#>  B,C - A,D    1.327 0.0781 143 16.986  <.0001 
#>  B,C - B,D    0.554 0.2289 143  2.422  0.0775 
#>  A,D - B,D   -0.773 0.2357 143 -3.279  0.0071 
#> 
#> factor3 = F:
#>  contrast  estimate     SE  df t.ratio p.value
#>  A C - B C   nonEst     NA  NA     NA      NA 
#>  A C - A D   nonEst     NA  NA     NA      NA 
#>  A C - B D   nonEst     NA  NA     NA      NA 
#>  B C - A D    1.470 0.3270 143  4.496  0.0001 
#>  B C - B D    1.282 0.3333 143  3.846  0.0010 
#>  A D - B D   -0.188 0.1198 143 -1.571  0.3984 
#> 
#> P value adjustment: tukey method for comparing a family of 4 estimates
```

<sup>Created on 2020-05-23 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

As you can see, in one case the levels are separated by a comma, and not in the other. This leads then to some problems in the post-processing. I'll open an issue on emmeans to see if that's expected

**Comment by franrodalg** [comment]
I actually opened that issue there myself yesterday. It seems that it has now been corrected, although I am not sure when the fixed version will be released.

**Comment by DominiqueMakowski** [comment]
awesome!! indeed it seems like after updating emmeans from github the problem is gone:

``` r

    data <- iris
    data$factor1 <- ifelse(data$Sepal.Width > 3, "A", "B")
    data$factor2 <- ifelse(data$Petal.Length > 3.5, "C", "D")
    data$factor3 <- ifelse(data$Sepal.Length > 5, "E", "F")

    model <- lm(Petal.Width ~ factor1 * factor2 * factor3, data=data)
    modelbased::estimate_contrasts(model, modulate="factor3")
#> Level1 | Level2 | factor3 | Difference |   SE |         95% CI |     t |  df |      p | Difference (std.)
#> ---------------------------------------------------------------------------------------------------------
#> A C    |    A D |       E |       1.73 | 0.09 | [ 1.48,  1.98] | 18.51 | 143 | < .001 |              2.27
#> A C    |    A D |       F |            |      |                |       |     |        |                  
#> A C    |    B C |       E |       0.40 | 0.07 | [ 0.20,  0.60] |  5.37 | 143 | < .001 |              0.52
#> A C    |    B C |       F |            |      |                |       |     |        |                  
#> A C    |    B D |       E |       0.95 | 0.23 | [ 0.33,  1.58] |  4.07 | 143 | < .001 |              1.25
#> A C    |    B D |       F |            |      |                |       |     |        |                  
#> A D    |    B D |       E |      -0.77 | 0.24 | [-1.40, -0.14] | -3.28 | 143 | 0.003  |             -1.01
#> A D    |    B D |       F |      -0.19 | 0.12 | [-0.51,  0.13] | -1.57 | 143 | 0.474  |             -0.25
#> B C    |    A D |       E |       1.33 | 0.08 | [ 1.12,  1.54] | 16.99 | 143 | < .001 |              1.74
#> B C    |    A D |       F |       1.47 | 0.33 | [ 0.60,  2.34] |  4.50 | 143 | < .001 |              1.93
#> B C    |    B D |       E |       0.55 | 0.23 | [-0.06,  1.17] |  2.42 | 143 | 0.017  |              0.73
#> B C    |    B D |       F |       1.28 | 0.33 | [ 0.39,  2.17] |  3.85 | 143 | < .001 |              1.68
```

<sup>Created on 2020-05-23 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

nice catch :)

**Comment by franrodalg** [comment]
wonderful! I had no idea that the two issues that I noticed yesterday were in any way related heheh but glad to have helped!

**Comment by rvlenth** [comment]
Glad that fixed it!
