### ISSUE TITLE
estimate_contrasts dealing with three factors

### ISSUE THREAD

**Issue by goesjon** [easystats/modelbased#53]
Hello,

I have an issue with `estimate_contrasts()` when dealing with three factors (when dealing with two factors, it works fine). Try out the following code (thanks to @DominiqueMakowski ):

```r
library(modelbased)

df <- iris
df$factor1 <- ifelse(df$Sepal.Width > 3, "A", "B")
df$factor2 <- ifelse(df$Petal.Length > 3.5, "C", "D")
df$factor3 <- ifelse(df$Sepal.Length > 5, "E", "F")

model <- lm(Petal.Width ~ factor1 * factor2 * factor3, data=df)
estimate_contrasts(model, levels = "factor1")
```

{I choose as an example "factor1", but it does not matter if "factor1" or "factor2" or "factor3"}
"NOTE: Results may be misleading due to involvement in interactions"
{The NOTE is correct and helpful} 
{The output looks like follows, so basically there is no output}

```
#> Level1 | Level2 | Difference | SE | 95% CI | z | df | p | Difference (std.)
#> ---------------------------------------------------------------------------
#> A      |      B |            |    |        |   |    |   |                  
                                       
1: In max(unlist(lapply(stats::na.omit(CI_low), function(.i) nchar(as.character(.i))))) :
  no non-missing arguments to max; returning -Inf
2: In max(unlist(lapply(stats::na.omit(CI_high), function(.i) nchar(as.character(.i))))) :
  no non-missing arguments to max; returning -Inf
```

Do I do something wrong? Is this desired behavior? How do I get the contrasts of only one factor? 

Help would be very much appreciated.

Thank you very much and stay healthy!

**Comment by DominiqueMakowski** [comment]
``` r
df <- iris
df$factor1 <- ifelse(df$Sepal.Width > 3, "A", "B")
df$factor2 <- ifelse(df$Petal.Length > 3.5, "C", "D")
df$factor3 <- ifelse(df$Sepal.Length > 5, "E", "F")

model <- lm(Petal.Width ~ factor1 * factor2 * factor3, data=df)
emmeans::emmeans(model, "factor1")
#> NOTE: Results may be misleading due to involvement in interactions
#>  factor1 emmean    SE  df lower.CL upper.CL
#>  A       nonEst    NA  NA       NA       NA
#>  B         1.19 0.101 143    0.993     1.39
#> 
#> Results are averaged over the levels of: factor2, factor3 
#> Confidence level used: 0.95
```

<sup>Created on 2020-04-16 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>


It seems this is directly related to the marginal means estimation (as modelbased wraps around `emmeans`), I think it's because the model is ill-specified, but it should work on some data with enough observations in each combination of factors

**Comment by goesjon** [comment]
Hello @DominiqueMakowski 

thank you for your message. Indeed, if I exclude the three way interaction factor1:factor2:factor3, the code works:

``` r
df <- iris
df$factor1 <- ifelse(df$Sepal.Width > 3, "A", "B")
df$factor2 <- ifelse(df$Petal.Length > 3.5, "C", "D")
df$factor3 <- ifelse(df$Sepal.Length > 5, "E", "F")

model <- lm(Petal.Width ~ factor1 * factor2 + factor3 + factor2:factor3, data=df)
modelbased::estimate_contrasts(model, levels = "factor1")
#> NOTE: Results may be misleading due to involvement in interactions
#> Level1 | Level2 | Difference |   SE |        95% CI |    t |  df |     p | Difference (std.)
#> --------------------------------------------------------------------------------------------
#> A      |      B |       0.05 | 0.07 | [-0.08, 0.18] | 0.69 | 144 | 0.489 |              0.06
```

As soon as I add the three way interaction again, the previous error messages reappear. A warning would be nice, which tells, that the model is ill-specified for this purpose, because the current error messages are difficult to interpret (which lead me to believe it might be a bug, although it was my inability all along).  

The point is, that I get the previous error messages also with my original code, which deals with a big lmer model. Now I must assume that this big lmer model is ill-specified? I have to see how I deal with that. 

Anyway, thank you very much for your time and help. I really appreciate it. 

I close this issue.

**Comment by DominiqueMakowski** [comment]
As the error originates in the `emmeans` package, unfortunately, it's kinda hard to detect and throw relevant warnings in `modelbased` 😕
