### ISSUE TITLE
Error when estimating contrasts for interaction variable that has only two factors

### ISSUE THREAD

**Issue by favstats** [easystats/modelbased#54]
Hi!

Love your package, thanks for all the hard work!

I have a dataset that has a factor variable with two values. I tried to estimate contrasts with a numeric interaction but I am getting an error.

Here is a reproducible example:

`## only leave in two values for Species`
`iris_2FA<- iris[which(iris$Species %in% c("versicolor", "setosa")),]`
`## estimate model`
`model <- lm(Sepal.Width ~ Species * Petal.Width, data = iris_2FA)`
`## estimate contrasts`
`estimate_contrasts(model, modulate = "Petal.Width", length = 4)`

Leads to the following error:
`Error in names(levelcols) <- c("Level1", "Level2") : 'names' attribute [2] must be the same length as the vector [0]`

The error occurs here:
https://github.com/easystats/modelbased/blob/9eae1cc4f7cef5e7ac5a701e555b1523aef34e4a/R/estimate_contrasts.frequentist.R#L74

**Comment by DominiqueMakowski** [comment]
Could be related to #51, I'll give it a look asap

**Comment by DominiqueMakowski** [comment]
@favstats sorry for the delay, it should be fixed on the dev branch now ☺️
