### ISSUE TITLE
Problem with as.factor in formula

### ISSUE THREAD

**Issue by DominiqueMakowski** [easystats/modelbased#60]
### This works

``` r
levels <- "gear"
data <- mtcars
data$gear <- as.factor(data$gear)
model <- lm(mpg ~gear, data = data)

at <- insight::get_data(model)[levels]
at <- sapply(at, modelbased::visualisation_matrix, simplify = FALSE)

emmeans::ref_grid(model, at = at)
#> 'emmGrid' object with variables:
#>     gear = 3, 4, 5
```

### This doesn't
```r
levels <- "gear"
model <- lm(mpg ~as.factor(gear), data = mtcars)

at <- insight::get_data(model)[levels]
at <- sapply(at, modelbased::visualisation_matrix, simplify = FALSE)

emmeans::ref_grid(model, at = at)
#> Error in Math.factor(structure(1:3, .Label = c("3", "4", "5"), class = "factor"), : 'round' not meaningful for factors
```

<sup>Created on 2020-05-19 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

@mattansb @strengejacke any ideas on how to best address?

**Comment by mattansb** [comment]
The values of the "at" argument should type/value match the *original* data, and it internally dows any transformations etc. 
In this case, `gear` is numeric (kinda), so:

``` r
model <- lm(mpg ~as.factor(gear), data = mtcars)

emmeans::ref_grid(model, at = list(gear = c(3,4,5)))
#> 'emmGrid' object with variables:
#>     gear = 3, 4, 5
```

<sup>Created on 2020-05-19 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>


This is also why these two give the same result:

``` r
m1 <- lm(mpg ~ wt, data = mtcars)
m2 <- lm(mpg ~ scale(wt), data = mtcars)


emmeans::emmeans(m1, ~ wt, at = list(wt = 3))
#>  wt emmean    SE df lower.CL upper.CL
#>   3   21.3 0.552 30     20.1     22.4
#> 
#> Confidence level used: 0.95
emmeans::emmeans(m2, ~ wt, at = list(wt = 3))
#>  wt emmean    SE df lower.CL upper.CL
#>   3   21.3 0.552 30     20.1     22.4
#> 
#> Confidence level used: 0.95
```

<sup>Created on 2020-05-19 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by strengejacke** [comment]
> This is also why these two give the same result:

I think this is because the association is actually the same, it does not change when you scale your input (the coefficients do, not the "slope"). With `predict()` you get also identical results:

``` r
m1 <- lm(mpg ~ wt, data = mtcars)
m2 <- lm(mpg ~ scale(wt), data = mtcars)
library(ggeffects)

ggpredict(m1, "wt [3]")
#> 
#> # Predicted values of mpg
#> # x = wt
#> 
#> x | Predicted |   SE |         95% CI
#> -------------------------------------
#> 3 |     21.25 | 0.55 | [20.17, 22.33]

ggpredict(m2, "wt [3]")
#> 
#> # Predicted values of mpg
#> # x = wt
#> 
#> x | Predicted |   SE |         95% CI
#> -------------------------------------
#> 3 |     21.25 | 0.55 | [20.17, 22.33]
```

<sup>Created on 2020-05-19 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by DominiqueMakowski** [comment]
but this is annoying because it makes changing type in the formula fail with emmeans with the new implementation of its wrapper:

https://github.com/easystats/modelbased/blob/a852fe854cf6f28740c3ce0a3567e953fdf40a5f/R/utils_emmeans_wrapper.R#L68-L83

And the only way to easily accommodate would be in insight? So that it returns non-modified data?

Worst case scenario we can just do nothing, since modifying types in formulas is not recommended anyway, but...

**Comment by mattansb** [comment]
@strengejacke I have no idea how predict works - I am only an emmeans expert! 😅🤪

**Comment by strengejacke** [comment]
> @strengejacke I have no idea how predict works - I am only an emmeans expert! 😅🤪

;-)

They work [pretty similar](https://strengejacke.github.io/ggeffects/articles/technical_differencepredictemmeans.html) - though not exactly the same.

**Comment by strengejacke** [comment]
>  So that it returns non-modified data?

I'm not sure how to detect if data is non-modified? But I think that emmeans either requires numerics, if really "numeric" (including numeric factor levels), and else the character version (see below).

``` r
levels <- "gear"
data(mtcars)
mtcars$gear <- factor(sjmisc::rec(mtcars$gear, rec = "3=a;4=b;5=c"))
model <- lm(mpg ~gear, data = mtcars)

at <- insight::get_data(model)[levels]
at <- sapply(at, modelbased::visualisation_matrix, simplify = FALSE)

emmeans::ref_grid(model, at = at)
#> 'emmGrid' object with variables:
#>     gear = a, b, c
```

<sup>Created on 2020-05-19 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

Thus, check if factor `at` has numeric levels:
`is.factor(x) && !anyNA(suppressWarnings(as.numeric(levels(x))))`

and if so, convert to numeric before passing to sapply(vismatrix).

**Comment by strengejacke** [comment]
Does that work? (I hope so...)

**Comment by strengejacke** [comment]
Seems it works:

``` r
data(mtcars)
levels <- "gear"
model <- lm(mpg ~as.factor(gear), data = mtcars)

at <- insight::get_data(model)[levels]
at <- sapply(at, modelbased::visualisation_matrix, simplify = FALSE)

.numeric_levels <- function(x) {
  is.factor(x) && !anyNA(suppressWarnings(as.numeric(levels(x))))
}

at <- lapply(at, function(i) {
  if (.numeric_levels(i)) {
    as.numeric(levels(i))
  } else {
    i
  }
})

emmeans::ref_grid(model, at = at)
#> 'emmGrid' object with variables:
#>     gear = 3, 4, 5
```

<sup>Created on 2020-05-19 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by DominiqueMakowski** [comment]
``` r
data(mtcars)
levels <- "gear"
data <- mtcars
data$gear <- as.factor(data$gear)
model <- lm(mpg ~gear, data = data)

at <- insight::get_data(model)[levels]
at <- sapply(at, modelbased::visualisation_matrix, simplify = FALSE)

.numeric_levels <- function(x) {
  is.factor(x) && !anyNA(suppressWarnings(as.numeric(levels(x))))
}

at <- lapply(at, function(i) {
  if (.numeric_levels(i)) {
    as.numeric(levels(i))
  } else {
    i
  }
})

emmeans::ref_grid(model, at = at)
#> Error in `contrasts<-`(`*tmp*`, value = contrasts.arg[[nn]]): contrasts apply only to factors
```

<sup>Created on 2020-05-19 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>


Doesn't work then it the regular case, need to find a way to conditionally run this fix

**Comment by DominiqueMakowski** [comment]
Because I think the issue is that the pulled variable from the model's data (through insight::get_data()) does not match the type of the variable in the model, as the latter has been changed "in the formula", which doesn't affect the data in the model.

**Comment by DominiqueMakowski** [comment]
You might have a more clever idea than my patch 😁
