### ISSUE TITLE
issue with estimate_contrasts

### ISSUE THREAD

**Issue by goesjon** [easystats/modelbased#61]
Hello,

firstly I have to say that I like the easystats packages very much, thank you. 

Having said that, I would like to report an issue with estimate_contrasts. It does not accept anymore formula as levels. An example:

```r library(modelbased)
df <- iris
df$factor1 <- ifelse(df$Sepal.Width > 3, "A", "B")
df$factor2 <- ifelse(df$Petal.Length > 3.5, "C", "D")
model <- lm(Petal.Width ~ factor1 * factor2, data=df)
estimate_contrasts(model, levels = ~ "factor1 * factor2")
#> Error in `[.default`(insight::get_data(model), levels): invalid subscript type 'list'
```
This code worked till some time, but now not anymore. In the documentation of `estimate_contrasts` it says: 

> levels - A character vector or formula specifying the names of the predictors over which to estimate means or contrasts.

How do I specify the formula now? 

Thank you very much.

Best regards

**Comment by DominiqueMakowski** [comment]
@goesjon with the new version that you can install from dev, you can do:

``` r
library(modelbased)
df <- iris
df$factor1 <- ifelse(df$Sepal.Width > 3, "A", "B")
df$factor2 <- ifelse(df$Petal.Length > 3.5, "C", "D")
model <- lm(Petal.Width ~ factor1 * factor2, data=df)
estimate_contrasts(model, levels = ~ factor1 * factor2)
#> Level1 | Level2 | Difference |   SE |        95% CI |     t |  df |      p | Difference (std.)
#> ----------------------------------------------------------------------------------------------
#> A - C  |  A - D |       1.75 | 0.08 | [ 1.53, 1.97] | 21.41 | 146 | < .001 |              2.29
#> A - C  |  B - C |       0.40 | 0.08 | [ 0.20, 0.60] |  5.29 | 146 | < .001 |              0.52
#> A - C  |  B - D |       1.49 | 0.11 | [ 1.19, 1.78] | 13.46 | 146 | < .001 |              1.95
#> A - D  |  B - D |      -0.26 | 0.10 | [-0.54, 0.01] | -2.54 | 146 | 0.012  |             -0.34
#> B - C  |  A - D |       1.35 | 0.06 | [ 1.18, 1.52] | 21.40 | 146 | < .001 |              1.77
#> B - C  |  B - D |       1.09 | 0.10 | [ 0.83, 1.35] | 11.16 | 146 | < .001 |              1.43
```

<sup>Created on 2020-05-20 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>


(note that a formula has no `"`). Hope it helps

**Comment by goesjon** [comment]
Hello @DominiqueMakowski 

many thanks for your help. I re-installed the package already yesterday with `devtools::install_github("easystats/modelbased", "dev")` which did not help. I also tried all kind of combinations of `~` `=` `"`, did not work. 

Today again, and yes, suddenly it works (without `"` as well as with `"`), did something change since yesterday? 

Anyway, issue solved, issue closed. Thanks again :)

Best regards and stay healthy
