### ISSUE TITLE
Deal seriously with the random effects for freq models

### ISSUE THREAD

**Issue by DominiqueMakowski** [easystats/modelbased#74]

**Comment by strengejacke** [comment]
What do you mean? Is it related to https://github.com/easystats/modelbased/issues/57?

**Comment by DominiqueMakowski** [comment]
Pretty much yeah doing my stats I ran into some problems and it made me feel like it's worth regiving it a look, cause from what I remember previously it was possible to get predictions from lmer models with new data without random effects and now it's not

**Comment by strengejacke** [comment]
You can set the variable of the random effects to `NA`. This is what I did for glmmTMB. Then you get predictions on the population level.

**Comment by strengejacke** [comment]
https://github.com/easystats/modelbased/blob/ea26c3eefe08a416e5b2302f1a6327cd5ebdc98f/R/visualisation_matrix.R#L62
