### ISSUE TITLE
`estimate_means` for BFBayesFactor model object or data frame from `weighted_posteriors`

### ISSUE THREAD

**Issue by nahorp** [easystats/modelbased#82]
Hello,

I'm trying to obtain centrality (means or medians) as well as uncertainty (credible intervals) measures for different levels of a categorical factor . I realised that `emmeans` doesn't accept `BFBayesFactor` model types and came across the `estimate_means` function that would give me the marginal means I want. Couple of questions,

1) Is there a plan to include `BFBayesFactor` model types for use with `estimate_means`?

2) If not, I realised that I can obtain the weighted posterior estimates from a `BFBayesFactor` model object using the `weighted_posteriors` function in bayestestR. Is it possible to use the data frame that is output from `weighted_posteriors` to use with `estimate_means`?

Thank you

**Comment by DominiqueMakowski** [comment]
1. No as, `estimate_means` relies on emmeans, so if no emmeans support, then no modelbased 😕 

2. I don't think so, as estimate_means (i.e., `emmeans` behind the scene) requires some more information about the model (if I'm not mistaken @mattansb)

**Comment by mattansb** [comment]
Unfortunately there is not way to automatically get estimates from `BayesFactor` objects or from  `weighted_posteriors()` results... Only manually...

**Comment by nahorp** [comment]
Bummer... Oh well, thanks @DominiqueMakowski and @mattansb for the quick response, appreciate it.
