### ISSUE TITLE
robustlmer and estimate_slopes()

### ISSUE THREAD

**Issue by Ann1Ko** [easystats/modelbased#83]
Is there any chance to use an rlmerMod Model and estimate_slopes() in the near future? I'm trying to compare slopes of an robust Model at different factor levels, but so far I did not find any solution.

**Comment by strengejacke** [comment]
_modelbased_ completely relies on _emmeans_, so it's actually not in our control which packages are supported and which not. At the moment, _emmeans_ does not support rlmerMod models.

I guess you could either ask the maintainer of the emmeans package to implement support, or ask the maintainers of the rlmerMod package to do so (emmeans has an object oriented API that allows package developers to directly add support for emmeans).

**Comment by Ann1Ko** [comment]
Ok! Thanks, I'm going to do that.

**Comment by IndrajeetPatil** [comment]
Closing in favor of: https://github.com/rvlenth/emmeans/issues/240
