### ISSUE TITLE
include_sooth fails when no smooth 

### ISSUE THREAD

**Issue by DominiqueMakowski** [easystats/modelbased#88]
it should just be ignored
``` r
m <- lm(Sepal.Length ~ Petal.Width, data=iris)
modelbased::estimate_link(m, include_smooth=FALSE)
#> Error in f$conditional[[2L]]: subscript out of bounds
```

<sup>Created on 2020-12-10 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by strengejacke** [comment]
`insight::find_smooth()` should be in the CRAN version, and return `NULL` if no smooth term present. You could use that to check.
