### ISSUE TITLE
Estimating within-person variability with (Bayesian) mixed models

### ISSUE THREAD

**Issue by DominiqueMakowski** [easystats/modelbased#94]
@mattansb recently @IndrajeetPatil mentioned the paper by [Williams et al., 2021](https://psycnet.apa.org/record/2020-33519-001) in which they estimate the "variability" of participants as random factors. They used JAGS, but you mentioned that it could be feasible with brms.

This could be a great thing to add to a tutorial, as I believe it would be of interest to many.

Here's some toy code to create a dataframe with a variable to predict (RT):

``` r
library(brms)

n_particpants <- 10
n_trials <- 10

estimates <- rnorm(n_particpants, 100, 15)
variabilities <- abs(rnorm(n_particpants, 0, 5))

data <- data.frame()
for(participant in 1:n_particpants) {
  data <- rbind(data, 
                data.frame(
                  Participant = sprintf("S%02d", participant),
                  RT = rnorm(n_trials, estimates[participant], variabilities[participant])
                  )
                )
}

model <- brms::brm(RT ~ 1 + (1|Participant), data=data, refresh = 0)

random <- bayestestR::describe_posterior(insight::get_parameters(model, effects = "random"), dispersion = TRUE)[1:10, ]

cor.test(random$Median, estimates)  # Yay!
#>       cor 
#> 0.9992399

cor.test(random$MAD, variabilities)  # Nope
#>       cor 
#> 0.2891431
```

<sup>Created on 2021-02-28 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

The "average" estimate of each participant is easy to retrieve through this random intercept specification, but, contrary to a naive view, the **uncertainty of the estimation is absolutely not equivalent to the variability in the data**.

How can we modelize this within-participant variability?

**Comment by mattansb** [comment]
```R
library(brms)

model_spec <- brmsformula(
  RT ~ 1 + (1|G|Participant),
  sigma ~ 1 + (1|G|Participant)
)

model <- brms::brm(model_spec, data = data)
```
Where `sigma` is the "level" 1 error - or within subject variability.

Note the special syntax (`(1|G|Participant)`) that allows for a correlation between the random effects across parameter types (mean / sigma).

This can be extended to any family, e.g.:

```R
model_spec <- brmsformula(
  RT ~ 1 + (1|G|Participant),
  beta ~ 1 + (1|G|Participant), # beta is the "tau"
  sigma ~ 1 + (1|G|Participant)
)

model <- brms::brm(model_spec, data = data, family = exgaussian())
```

**Comment by DominiqueMakowski** [comment]
``` r
formula <- brms::brmsformula(
  RT ~ 1 + (1|G|Participant),
  sigma ~ 1 + (1|G|Participant)
)

model <- brms::brm(formula, data=data, refresh = 0, backend="cmdstanr")
params <- bayestestR::describe_posterior(insight::get_parameters(model, effects = "random"), dispersion = TRUE)


cor.test(params$Median[21:30], estimates)  # Yay!
#>       cor 
#> 0.9935236
cor.test(params$Median[31:40], variabilities)  # Yay!
#>       cor 
#> 0.8902564
```

<sup>Created on 2021-02-28 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>



![](https://media.giphy.com/media/Um3ljJl8jrnHy/giphy.gif)

**Comment by DominiqueMakowski** [comment]
![image](https://user-images.githubusercontent.com/8875533/109423515-aae7fa00-7a1a-11eb-8d35-69b650486244.png)

The printing of these parameters is somewhat confusing tho, @strengejacke do you recall if this is controlled by clean_parameters or pretty_names?

**Comment by DominiqueMakowski** [comment]
And a hundred thanks @mattansb, you made my night 😁

**Comment by mattansb** [comment]
Enjoy!
Don't forget to add me to your paper's acknowledgments! 🤓

**Comment by strengejacke** [comment]
Am I missing something here, or can't you achieve the same thing with a "simple" mixed model?

``` r
library(lme4)
#> Loading required package: Matrix
library(parameters)

set.seed(333)
n_particpants <- 10
n_trials <- 10

estimates <- rnorm(n_particpants, 100, 15)
variabilities <- abs(rnorm(n_particpants, 0, 5))

data <- data.frame()
for(participant in 1:n_particpants) {
  data <- rbind(data, 
                data.frame(
                  Participant = sprintf("S%02d", participant),
                  RT = rnorm(n_trials, estimates[participant], variabilities[participant])
                )
  )
}

model <- lmer(RT ~ 1 + (1 | Participant), data = data)

model_parameters(model) # intercept: ~ average estimates
#> Parameter   | Coefficient |   SE |          95% CI | t(97) |      p
#> -------------------------------------------------------------------
#> (Intercept) |       99.73 | 5.60 | [88.75, 110.72] | 17.80 | < .001

# SD of within and between group-variance match
# SD from estimates and variabilities
random_parameters(model) 
#> # Random Effects
#> 
#> Within-Group Variance              13.98  (3.74)
#> Between-Group Variance
#>   Random Intercept (Participant)  312.69 (17.68)
#> N (groups per factor)
#>   Participant                         10
#> Observations                         100

sd(variabilities)
#> [1] 2.318507
sd(estimates)
#> [1] 17.88566
```

<sup>Created on 2021-02-28 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

**Comment by strengejacke** [comment]
Same for Bayesian version:

``` r
library(brms)

set.seed(333)
n_particpants <- 10
n_trials <- 10

estimates <- rnorm(n_particpants, 100, 15)
variabilities <- abs(rnorm(n_particpants, 0, 5))

data <- data.frame()
for(participant in 1:n_particpants) {
  data <- rbind(data, 
                data.frame(
                  Participant = sprintf("S%02d", participant),
                  RT = rnorm(n_trials, estimates[participant], variabilities[participant])
                )
  )
}

model <- brm(RT ~ 1 + (1 | Participant), data = data, cores = 4)

# average estimate
mean(as.data.frame(model)$b_Intercept)
#> [1] 100.1158

# SDs
insight::get_sigma(model)
#> var.residual 
#>     3.783963 
mean(as.data.frame(model)$sigma)
#> [1] 3.783963
sd(variabilities)
#> [1] 2.318507

mean(as.data.frame(model)$sd_Participant__Intercept)
#> [1] 18.14047
sd(estimates)
#> [1] 17.88566
```

<sup>Created on 2021-02-28 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

**Comment by DominiqueMakowski** [comment]
the above methods return the variability and the estimates for *each* participant (and not the general variability), whch can be used as interindividual differences

**Comment by mattansb** [comment]
With normal mixed model you can't continue to model the intra-subject variability (isv). E.g., adhd is associated with higher isv... 

```r
brmsformula(
  RT ~ adhd + (1|G|subject), # adhd is related to differences in mean RT
  sigma ~ adhd + (1|G|subject) # adhd is related to differences in RT variability
)
```

The common way to model this (so far) is to residualize participants data and then computing the sample sd per subject. But modeling it directly gives full power of shrinkage, and the ability to extend the model...

**Comment by strengejacke** [comment]
Ok, got it!
